CREATE SEQUENCE IF NOT EXISTS yaya_content_season_seq;
CREATE SEQUENCE IF NOT EXISTS yaya_import_batch_seq;
CREATE SEQUENCE IF NOT EXISTS yaya_practice_topic_seq;
CREATE SEQUENCE IF NOT EXISTS yaya_practice_question_seq;
CREATE SEQUENCE IF NOT EXISTS yaya_topic_relation_seq;
CREATE SEQUENCE IF NOT EXISTS yaya_tag_seq;
CREATE SEQUENCE IF NOT EXISTS yaya_topic_tag_seq;
CREATE SEQUENCE IF NOT EXISTS yaya_favorite_seq;
CREATE SEQUENCE IF NOT EXISTS yaya_user_topic_state_seq;
CREATE SEQUENCE IF NOT EXISTS yaya_practice_attempt_seq;
CREATE SEQUENCE IF NOT EXISTS yaya_ai_task_seq;
CREATE SEQUENCE IF NOT EXISTS yaya_recording_seq;
CREATE SEQUENCE IF NOT EXISTS yaya_evaluation_seq;
CREATE SEQUENCE IF NOT EXISTS yaya_member_plan_seq;
CREATE SEQUENCE IF NOT EXISTS yaya_member_entitlement_seq;

CREATE TABLE IF NOT EXISTS "yaya_content_season" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "season_key" varchar(40) NOT NULL,
    "name" varchar(120) NOT NULL,
    "active" tinyint NOT NULL DEFAULT 1,
    "defaulted" tinyint NOT NULL DEFAULT 0,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "yaya_import_batch" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "season_key" varchar(40) NOT NULL,
    "source_label" varchar(120) NOT NULL,
    "status" varchar(40) NOT NULL,
    "summary" varchar(4000) NOT NULL DEFAULT '{}',
    "created_by" varchar(120) NOT NULL DEFAULT 'local-admin',
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "yaya_practice_topic" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "legacy_uuid" varchar(64),
    "season_id" bigint NOT NULL,
    "source_snapshot_id" bigint,
    "part" tinyint NOT NULL,
    "stable_key" varchar(180) NOT NULL,
    "topic_no" int,
    "title_en" text NOT NULL DEFAULT '',
    "title_zh" text NOT NULL DEFAULT '',
    "topic_type" varchar(80) NOT NULL DEFAULT '',
    "category" varchar(120) NOT NULL DEFAULT '',
    "prompt_en" text NOT NULL DEFAULT '',
    "prompt_zh" text NOT NULL DEFAULT '',
    "display_order" int NOT NULL DEFAULT 0,
    "review_status" varchar(40) NOT NULL DEFAULT 'draft',
    "publish_status" varchar(40) NOT NULL DEFAULT 'draft',
    "metadata" varchar(4000) NOT NULL DEFAULT '{}',
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "yaya_practice_question" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "legacy_uuid" varchar(64),
    "topic_id" bigint NOT NULL,
    "question_role" varchar(60) NOT NULL DEFAULT 'question',
    "prompt_en" text NOT NULL DEFAULT '',
    "prompt_zh" text NOT NULL DEFAULT '',
    "cue_bullets" varchar(4000) NOT NULL DEFAULT '[]',
    "display_order" int NOT NULL DEFAULT 0,
    "prepare_seconds" int,
    "answer_seconds" int,
    "metadata" varchar(4000) NOT NULL DEFAULT '{}',
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "yaya_topic_relation" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "source_topic_id" bigint NOT NULL,
    "target_topic_id" bigint NOT NULL,
    "relation_type" varchar(80) NOT NULL DEFAULT 'part2_part3',
    "confidence" varchar(40) NOT NULL DEFAULT 'manual',
    "metadata" varchar(4000) NOT NULL DEFAULT '{}',
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "yaya_tag" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "tag_key" varchar(80) NOT NULL,
    "label" varchar(120) NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "yaya_topic_tag" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "topic_id" bigint NOT NULL,
    "tag_id" bigint NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "yaya_favorite" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "member_user_id" bigint NOT NULL,
    "topic_id" bigint NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id"),
    UNIQUE ("member_user_id", "topic_id")
);

CREATE TABLE IF NOT EXISTS "yaya_user_topic_state" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "member_user_id" bigint NOT NULL,
    "topic_id" bigint NOT NULL,
    "practiced" bit NOT NULL DEFAULT FALSE,
    "attempt_count" int NOT NULL DEFAULT 0,
    "last_attempt_id" bigint,
    "last_practiced_at" datetime,
    "metadata" varchar(4000) NOT NULL DEFAULT '{}',
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id"),
    UNIQUE ("member_user_id", "topic_id")
);

CREATE TABLE IF NOT EXISTS "yaya_practice_attempt" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "member_user_id" bigint NOT NULL,
    "topic_id" bigint NOT NULL,
    "status" varchar(40) NOT NULL DEFAULT 'submitted',
    "answer_text" text NOT NULL DEFAULT '',
    "duration_seconds" int,
    "metadata" varchar(4000) NOT NULL DEFAULT '{}',
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "yaya_ai_task" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "member_user_id" bigint NOT NULL,
    "recording_id" bigint NOT NULL,
    "topic_id" bigint NOT NULL,
    "task_key" varchar(80) NOT NULL,
    "task_type" varchar(40) NOT NULL DEFAULT 'evaluation',
    "status" varchar(40) NOT NULL DEFAULT 'PENDING',
    "request_payload" varchar(4000) NOT NULL DEFAULT '{}',
    "response_payload" varchar(4000) NOT NULL DEFAULT '{}',
    "result_payload" varchar(4000) NOT NULL DEFAULT '{}',
    "error_payload" varchar(4000) NOT NULL DEFAULT '{}',
    "accepted_at" datetime,
    "completed_at" datetime,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id"),
    UNIQUE ("task_key")
);

CREATE TABLE IF NOT EXISTS "yaya_recording" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "member_user_id" bigint NOT NULL,
    "topic_id" bigint,
    "question_id" bigint,
    "attempt_id" bigint,
    "storage_path" text NOT NULL,
    "mime_type" varchar(120) NOT NULL,
    "size_bytes" bigint NOT NULL DEFAULT 0,
    "duration_seconds" double,
    "checksum" varchar(128) NOT NULL DEFAULT '',
    "status" varchar(40) NOT NULL DEFAULT 'stored',
    "metadata" varchar(4000) NOT NULL DEFAULT '{}',
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "yaya_evaluation" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "member_user_id" bigint NOT NULL,
    "recording_id" bigint,
    "topic_id" bigint,
    "ai_task_id" bigint,
    "status" varchar(40) NOT NULL DEFAULT 'PENDING',
    "provider" varchar(80) NOT NULL DEFAULT '',
    "model" varchar(120) NOT NULL DEFAULT '',
    "score_overall" double,
    "scores" varchar(4000) NOT NULL DEFAULT '{}',
    "report" varchar(4000) NOT NULL DEFAULT '{}',
    "text_route_scores" varchar(4000) NOT NULL DEFAULT '{}',
    "audio_route_scores" varchar(4000) NOT NULL DEFAULT '{}',
    "pron_route_scores" varchar(4000) NOT NULL DEFAULT '{}',
    "fluency_metrics" varchar(4000) NOT NULL DEFAULT '{}',
    "band_lower" double,
    "band_upper" double,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "yaya_member_plan" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "plan_key" varchar(80) NOT NULL,
    "name" varchar(120) NOT NULL,
    "description" text NOT NULL DEFAULT '',
    "price_cent" bigint NOT NULL DEFAULT 0,
    "currency" varchar(12) NOT NULL DEFAULT 'CNY',
    "duration_days" int NOT NULL DEFAULT 30,
    "active" tinyint NOT NULL DEFAULT 1,
    "benefits" varchar(4000) NOT NULL DEFAULT '{}',
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id"),
    UNIQUE ("plan_key")
);

CREATE TABLE IF NOT EXISTS "yaya_member_entitlement" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "member_user_id" bigint NOT NULL,
    "plan_id" bigint NOT NULL,
    "source_type" varchar(40) NOT NULL,
    "source_id" bigint,
    "status" varchar(40) NOT NULL DEFAULT 'active',
    "starts_at" datetime NOT NULL,
    "ends_at" datetime NOT NULL,
    "idempotency_key" varchar(128) NOT NULL,
    "metadata" varchar(4000) NOT NULL DEFAULT '{}',
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id"),
    UNIQUE ("idempotency_key")
);
