
### chat角色 - list
GET {{baseUrl}}/ai/chat/role/list?pageNo=1&pageSize=20&search=
Authorization: {{token}}


### chat add
PUT {{baseUrl}}/ai/chat/role
Content-Type: application/json
Authorization: {{token}}

{
  "modelId": 1,
  "name": "小红书写作v1",
  "introduce": "采用gpt3.5模型，拥有小红书优质作者写作经验。",
  "classify": "writing",
  "enable": "open"
}


### chat update
POST {{baseUrl}}/ai/chat/role/6
Content-Type: application/json
Authorization: {{token}}

{
  "modelId": 1,
  "name": "小红书写作v1---hh😄",
  "introduce": "采用gpt3.5模型，拥有小红书优质作者写作经验。",
  "classify": "writing",
  "enable": "close"
}

### chat update
POST {{baseUrl}}/ai/chat/role/6/update-visibility
Content-Type: application/json
Authorization: {{token}}

{
  "enable": "open"
}



### chat update
DELETE {{baseUrl}}/ai/chat/role/1
Content-Type: application/json
Authorization: {{token}}


