
### chat角色 - list
GET {{baseUrl}}/ai/chat/role/list?pageNo=1&pageSize=20&search=
Authorization: {{token}}


### chat add
PUT {{baseUrl}}/ai/chat/role
Content-Type: application/json
Authorization: {{token}}

{
  "modelId": 1,
  "roleName": "小红书写作v1",
  "roleIntroduce": "采用gpt3.5模型，拥有小红书优质作者写作经验。",
  "roleSource": "system",
  "classify": "writing",
  "visibility": "public",
  "topK": 0.2,
  "topP": 0.4,
  "temperature": 0.7
}


### chat update
POST {{baseUrl}}/ai/chat/role/1
Content-Type: application/json
Authorization: {{token}}

{
  "modelId": 1,
  "roleName": "小红书写作v1---hh😄",
  "roleIntroduce": "采用gpt3.5模型，拥有小红书优质作者写作经验。",
  "roleSource": "system",
  "classify": "writing",
  "visibility": "public",
  "topK": 0.2,
  "topP": 0.4,
  "temperature": 0.7
}

### chat update
POST {{baseUrl}}/ai/chat/role/1/update-visibility
Content-Type: application/json
Authorization: {{token}}

{
  "visibility": "private"
}


