
### chat call
GET {{baseUrl}}/admin-api/ai/chat/model/list
Authorization: {{token}}


### chat call
PUT {{baseUrl}}/admin-api/ai/chat/model/add
Content-Type: application/json
Authorization: {{token}}

{
  "keyId": "1",
  "name": "小红书Ai写作大模型4.0",
  "model": "ERNIE 4.0",
  "platform": "yiyan",
  "sort": 100
}

### chat call
POST {{baseUrl}}/admin-api/ai/chat/model/update
Content-Type: application/json
Authorization: {{token}}

{
  "id": 9,
  "keyId": "1",
  "name": "小红书Ai写作大模型3.5 8k",
  "model": "ERNIE-3.5-8K",
  "platform": "yiyan",
  "sort": 100
}
