

### 登录

POST {{baseUrl}}/admin-api/system/auth/login
Content-Type: application/json
tenant-id: 1

{
    "username": "admin",
    "password": "123456",
    "captchaVerification": "PfcH6mgr8tpXuMWFjvW6YVaqrswIuwmWI5dsVZSg7sGpWtDCUbHuDEXl3cFB1+VvCC/rAkSwK8Fad52FSuncVg==",
    "socialCode": "1024",
    "socialState": "9b2ffbc1-7425-4155-9894-9d5c08541d62",
    "socialCodeValid": true
}

### chat call
GET {{baseUrl}}/ai/chat?prompt=中国怎么样&modal=qianWen
tenant-id: 1
Authorization: {{token}}



### chat call
GET {{baseUrl}}/ai/chatStream?prompt=苹果是什么颜色?&modal=yiYan3_5_8k
tenant-id: 1
Authorization: {{token}}




