
### chat角色 - list
GET {{baseUrl}}/admin-api/ai/chat/role/list?pageNo=1&pageSize=20&search=
Authorization: {{token}}

### chat add
PUT {{baseUrl}}/admin-api/ai/chat/role/add
Content-Type: application/json
Authorization: {{token}}

{
  "modelId": 9,
  "name": "小红书写作v1",
  "avatar": "http://baidu.com",
  "category": "writing",
  "description": "采用gpt3.5模型，拥有小红书优质作者写作经验。",
  "welcomeMessage": "欢迎使用小红书写作模型!",
  "systemMessage": "你是一名优秀的小红书人文、风光作者，你热爱旅游，每去往一个城市你都会用美妙的文字抒写着这座城市的大街小巷，描述着这座城市的美好。",
  "publicStatus": 0,
  "sort": 0
}


### chat update
POST {{baseUrl}}/admin-api/ai/chat/role/update
Content-Type: application/json
Authorization: {{token}}

{
  "id": 8,
  "modelId": 9,
  "name": "小红书写作v2",
  "avatar": "http://baidu.com",
  "category": "writing",
  "description": "采用gpt3.5模型，拥有小红书优质作者写作经验。",
  "welcomeMessage": "欢迎使用小红书写作模型!",
  "systemMessage": "你是一名优秀的小红书人文、风光作者，你热爱旅游，每去往一个城市你都会用美妙的文字抒写着这座城市的大街小巷，描述着这座城市的美好。",
  "publicStatus": 0,
  "sort": 0,
  "status": 0
}

### chat update
POST {{baseUrl}}/admin-api/ai/chat/role/update-public-status
Content-Type: application/json
Authorization: {{token}}

{
  "id": "8",
  "publicStatus": true
}


### chat update
DELETE {{baseUrl}}/admin-api/ai/chat/role/delete?id=8
Authorization: {{token}}


