
### chat call
GET {{baseUrl}}/ai/chat/modal/list
Authorization: {{token}}


### chat call
PUT {{baseUrl}}/ai/chat/modal
Content-Type: application/json
Authorization: {{token}}

{
  "name": "小红书Ai写作大模型4.0",
  "modal": "ERNIE 4.0",
  "platform": "yiyan",
  "imageUrl": "",
  "sort": 100,
  "config": {
    "topK": 0.6,
    "topP": 0.6,
    "temperature": 0.86,
    "maxTokens": 2048
  }
}

### chat call
POST {{baseUrl}}/ai/chat/modal/7
Content-Type: application/json
Authorization: {{token}}

{
  "name": "小红书Ai写作大模型-plus",
  "modal": "ERNIE-3.5-8K",
  "platform": "yiyan",
  "imageUrl": "",
  "sort": 1,
  "config": {
    "topK": 0.6,
    "topP": 0.6,
    "temperature": 0.86,
    "maxTokens": 2048
  }
}
