
### chat dallDrawing

POST {{baseUrl}}/admin-api/ai/image/dallDrawing
Content-Type: application/json
Authorization: {{token}}

{
  "modal": "dall-e-3",
  "size": "1024x1024",
  "style": "vivid",
  "prompt": "中国长城"
}


### chat midjourney

POST {{baseUrl}}/admin-api/ai/image/midjourney
Content-Type: application/json
Authorization: {{token}}

{
  "prompt": "Cute cartoon style mobile game scene, a colorful camping car with an outdoor table and chairs next to it on the road in a spring forest, the simple structure of the camper van, soft lighting, C4D rendering, 3d model in the style of a cartoon, cute shape, a pastel color scheme, closeup view from the side angle, high resolution, bright colors, a happy atmosphere."
}