### 创建错误码
POST {{baseUrl}}/inra/error-code/create
Authorization: Bearer {{token}}
Content-Type: application/json
tenant-id: {{adminTenentId}}

{
  "code": 200,
  "message": "成功",
  "group": "test",
  "type": 1
}

