
### 生成图片：OpenAI（DALL）
POST {{baseUrl}}/ai/image/draw
Content-Type: application/json
Authorization: {{token}}

{
  "platform": "OpenAI",
  "prompt": "可爱的小喵星人",
  "model": "dall-e-3",
  "height": "1024",
  "width": "1024",
  "options": {
    "style": "vivid"
  }
}

### 生成图片：StableDiffusion
POST {{baseUrl}}/ai/image/draw
Content-Type: application/json
Authorization: {{token}}

{
  "platform": "StableDiffusion",
  "prompt": "中国长城",
  "model": "stable-diffusion-v1-6",
  "height": "1024",
  "width": "1024",
  "style": "vivid"
}

### chat midjourney

POST {{baseUrl}}/admin-api/ai/image/midjourney
Content-Type: application/json
Authorization: {{token}}

{
  "prompt": "Cute cartoon style mobile game scene, a colorful camping car with an outdoor table and chairs next to it on the road in a spring forest, the simple structure of the camper van, soft lighting, C4D rendering, 3d model in the style of a cartoon, cute shape, a pastel color scheme, closeup view from the side angle, high resolution, bright colors, a happy atmosphere."
}