### 请求 /trade/cart/add-count 接口 => 成功
POST {{appApi}}/trade/cart/add-count
tenant-id: {{appTenentId}}
Authorization: Bearer {{appToken}}
Content-Type: application/json

{
  "skuId": 1,
  "count": 1
}

### 请求 /trade/cart/update-count 接口 => 成功
PUT {{appApi}}/trade/cart/update-count
tenant-id: {{appTenentId}}
Authorization: Bearer {{appToken}}
Content-Type: application/json

{
  "skuId": 1,
  "count": 5
}

### 请求 /trade/cart/update-selected 接口 => 成功
PUT {{appApi}}/trade/cart/update-selected
tenant-id: {{appTenentId}}
Authorization: Bearer {{appToken}}
Content-Type: application/json

{
  "skuIds": [1],
  "selected": false
}

### 请求 /trade/cart/delete 接口 => 成功
DELETE {{appApi}}/trade/cart/delete?skuIds=1
tenant-id: {{appTenentId}}
Authorization: Bearer {{appToken}}

### 请求 /trade/cart/get-count 接口 => 成功
GET {{appApi}}/trade/cart/get-count
tenant-id: {{appTenentId}}
Authorization: Bearer {{appToken}}

### 请求 /trade/cart/get-detail 接口 => 成功
GET {{appApi}}/trade/cart/get-detail
tenant-id: {{appTenentId}}
Authorization: Bearer {{appToken}}
