### 请求 /mp/free-publish/page 接口 => 成功
GET {{baseUrl}}/mp/free-publish/page?accountId=1&pageNo=1&pageSize=10
Content-Type: application/json
Authorization: Bearer {{token}}
tenant-id: {{adminTenentId}}

### 请求 /mp/free-publish/submit 接口 => 成功
POST {{baseUrl}}/mp/free-publish/submit?accountId=1&mediaId=r6ryvl6LrxBU0miaST4Y-vilmd7iS51D8IPddxflWrau0hIQ2ovY8YanO5jlgUcM
Content-Type: application/json
Authorization: Bearer {{token}}
tenant-id: {{adminTenentId}}

{}
