### 获取租户编号 /admin-api/system/get-id-by-name
GET {{baseUrl}}/system/tenant/get-id-by-name?name=芋道源码

### 创建租户 /admin-api/system/tenant/create
POST {{baseUrl}}/system/tenant/create
Content-Type: application/json
Authorization: Bearer {{token}}
tenant-id: {{adminTenantId}}

{
  "name": "芋道",
  "contactName": "芋艿",
  "contactMobile": "15601691300",
  "status": 0,
  "domain": "https://www.iocoder.cn",
  "packageId": 110,
  "expireTime": 1699545600000,
  "accountCount": 20,
  "username": "admin",
  "password": "123321"
}
