/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.somle.tiktok.sdk.model.Authorization.V202309;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.somle.tiktok.sdk.invoke.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * GetAuthorizedShopsResponseDataShops
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-12T06:25:14.052506Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class GetAuthorizedShopsResponseDataShops {
    public static final String SERIALIZED_NAME_CIPHER = "cipher";
    public static final String SERIALIZED_NAME_CODE = "code";
    public static final String SERIALIZED_NAME_ID = "id";
    public static final String SERIALIZED_NAME_NAME = "name";
    public static final String SERIALIZED_NAME_REGION = "region";
    public static final String SERIALIZED_NAME_SELLER_TYPE = "seller_type";
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("cipher");
        openapiFields.add("code");
        openapiFields.add("id");
        openapiFields.add("name");
        openapiFields.add("region");
        openapiFields.add("seller_type");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    @SerializedName(SERIALIZED_NAME_CIPHER)
    private String cipher;
    @SerializedName(SERIALIZED_NAME_CODE)
    private String code;
    @SerializedName(SERIALIZED_NAME_ID)
    private String id;
    @SerializedName(SERIALIZED_NAME_NAME)
    private String name;
    @SerializedName(SERIALIZED_NAME_REGION)
    private String region;
    @SerializedName(SERIALIZED_NAME_SELLER_TYPE)
    private String sellerType;

    public GetAuthorizedShopsResponseDataShops() {
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to GetAuthorizedShopsResponseDataShops
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GetAuthorizedShopsResponseDataShops.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format("The required field(s) %s in GetAuthorizedShopsResponseDataShops is not found in the empty JSON string", GetAuthorizedShopsResponseDataShops.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!GetAuthorizedShopsResponseDataShops.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetAuthorizedShopsResponseDataShops` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("cipher") != null && !jsonObj.get("cipher").isJsonNull()) && !jsonObj.get("cipher").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `cipher` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cipher").toString()));
        }
        if ((jsonObj.get("code") != null && !jsonObj.get("code").isJsonNull()) && !jsonObj.get("code").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("code").toString()));
        }
        if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
        }
        if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
        }
        if ((jsonObj.get("region") != null && !jsonObj.get("region").isJsonNull()) && !jsonObj.get("region").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `region` to be a primitive type in the JSON string but got `%s`", jsonObj.get("region").toString()));
        }
        if ((jsonObj.get("seller_type") != null && !jsonObj.get("seller_type").isJsonNull()) && !jsonObj.get("seller_type").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `seller_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("seller_type").toString()));
        }
    }

    /**
     * Create an instance of GetAuthorizedShopsResponseDataShops given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetAuthorizedShopsResponseDataShops
     * @throws IOException if the JSON string is invalid with respect to GetAuthorizedShopsResponseDataShops
     */
    public static GetAuthorizedShopsResponseDataShops fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, GetAuthorizedShopsResponseDataShops.class);
    }

    public GetAuthorizedShopsResponseDataShops cipher(String cipher) {
        this.cipher = cipher;
        return this;
    }

    /**
     * An encrypted token used to securely identify a shop in API requests. There is no need for decryption on the receiving end.
     *
     * @return cipher
     **/
    @javax.annotation.Nullable
    public String getCipher() {
        return cipher;
    }

    public void setCipher(String cipher) {
        this.cipher = cipher;
    }

    public GetAuthorizedShopsResponseDataShops code(String code) {
        this.code = code;
        return this;
    }

    /**
     * The TikTok Shop code, which is also displayed on Seller Center.
     *
     * @return code
     **/
    @javax.annotation.Nullable
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public GetAuthorizedShopsResponseDataShops id(String id) {
        this.id = id;
        return this;
    }

    /**
     * An internal identifier for the TikTok Shop.
     *
     * @return id
     **/
    @javax.annotation.Nullable
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public GetAuthorizedShopsResponseDataShops name(String name) {
        this.name = name;
        return this;
    }

    /**
     * The TikTok Shop name.
     *
     * @return name
     **/
    @javax.annotation.Nullable
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public GetAuthorizedShopsResponseDataShops region(String region) {
        this.region = region;
        return this;
    }

    /**
     * The region of the shop.
     *
     * @return region
     **/
    @javax.annotation.Nullable
    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public GetAuthorizedShopsResponseDataShops sellerType(String sellerType) {
        this.sellerType = sellerType;
        return this;
    }

    /**
     * The type of seller. Possible values: - CROSS_BORDER: Cross border sellers with multiple shops in different countries. - LOCAL: Local sellers with only 1 shop.
     *
     * @return sellerType
     **/
    @javax.annotation.Nullable
    public String getSellerType() {
        return sellerType;
    }

    public void setSellerType(String sellerType) {
        this.sellerType = sellerType;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetAuthorizedShopsResponseDataShops authorization202309GetAuthorizedShopsResponseDataShops = (GetAuthorizedShopsResponseDataShops) o;
        return Objects.equals(this.cipher, authorization202309GetAuthorizedShopsResponseDataShops.cipher) &&
            Objects.equals(this.code, authorization202309GetAuthorizedShopsResponseDataShops.code) &&
            Objects.equals(this.id, authorization202309GetAuthorizedShopsResponseDataShops.id) &&
            Objects.equals(this.name, authorization202309GetAuthorizedShopsResponseDataShops.name) &&
            Objects.equals(this.region, authorization202309GetAuthorizedShopsResponseDataShops.region) &&
            Objects.equals(this.sellerType, authorization202309GetAuthorizedShopsResponseDataShops.sellerType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(cipher, code, id, name, region, sellerType);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetAuthorizedShopsResponseDataShops {\n");
        sb.append("    cipher: ").append(toIndentedString(cipher)).append("\n");
        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    region: ").append(toIndentedString(region)).append("\n");
        sb.append("    sellerType: ").append(toIndentedString(sellerType)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert an instance of GetAuthorizedShopsResponseDataShops to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetAuthorizedShopsResponseDataShops.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'GetAuthorizedShopsResponseDataShops' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetAuthorizedShopsResponseDataShops> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(GetAuthorizedShopsResponseDataShops.class));

            return (TypeAdapter<T>) new TypeAdapter<GetAuthorizedShopsResponseDataShops>() {
                @Override
                public void write(JsonWriter out, GetAuthorizedShopsResponseDataShops value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public GetAuthorizedShopsResponseDataShops read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }
}

