-- 注意：！！！！！！
-- 注意：该脚本是在项目已经成功启用工作流模块，数据库自动生成了ACT_相关的表之后，再执行。
-- 如何启用工作流模块，请参考：https://doc.iocoder.cn/bpm/
-- 更详细的说明请看博客：https://blog.csdn.net/qq_31237581/article/details/130132221
ALTER TABLE ACT_GE_BYTEARRAY COMMENT = '通用的流程定义和流程资源';
ALTER TABLE ACT_GE_PROPERTY COMMENT = '系统相关属性';
ALTER TABLE ACT_HI_ACTINST COMMENT = '历史的流程实例';
ALTER TABLE ACT_HI_ATTACHMENT COMMENT = '历史的流程附件';
ALTER TABLE ACT_HI_COMMENT COMMENT = '历史的说明性信息';
ALTER TABLE ACT_HI_DETAIL COMMENT = '历史的流程运行中的细节信息';
ALTER TABLE ACT_HI_IDENTITYLINK COMMENT = '历史的流程运行过程中用户关系';
ALTER TABLE ACT_HI_PROCINST COMMENT = '历史的流程实例';
ALTER TABLE ACT_HI_TASKINST COMMENT = '历史的任务实例';
ALTER TABLE ACT_HI_VARINST COMMENT = '历史的流程运行中的变量信息';
ALTER TABLE ACT_ID_BYTEARRAY COMMENT = '二进制数据表';
ALTER TABLE ACT_ID_GROUP COMMENT = '用户组信息表';
ALTER TABLE ACT_ID_INFO COMMENT = '用户信息详情表';
ALTER TABLE ACT_ID_MEMBERSHIP COMMENT = '人与组关系表';
ALTER TABLE ACT_ID_PRIV COMMENT = '权限表';
ALTER TABLE ACT_ID_PRIV_MAPPING COMMENT = '用户或组权限关系表';
ALTER TABLE ACT_ID_PROPERTY COMMENT = '属性表';
ALTER TABLE ACT_ID_TOKEN COMMENT = '系统登录日志表';
ALTER TABLE ACT_ID_USER COMMENT = '用户表';
ALTER TABLE ACT_RE_DEPLOYMENT COMMENT = '部署单元信息';
ALTER TABLE ACT_RE_MODEL COMMENT = '模型信息';
ALTER TABLE ACT_RE_PROCDEF COMMENT = '已部署的流程定义';
ALTER TABLE ACT_RU_DEADLETTER_JOB COMMENT = '正在运行的任务表';
ALTER TABLE ACT_RU_EVENT_SUBSCR COMMENT = '运行时事件';
ALTER TABLE ACT_RU_EXECUTION COMMENT = '运行时流程执行实例';
ALTER TABLE ACT_RU_HISTORY_JOB COMMENT = '历史作业表';
ALTER TABLE ACT_RU_IDENTITYLINK COMMENT = '运行时用户关系信息';
ALTER TABLE ACT_RU_JOB COMMENT = '运行时作业表';
ALTER TABLE ACT_RU_SUSPENDED_JOB COMMENT = '暂停作业表';
ALTER TABLE ACT_RU_TASK COMMENT = '运行时任务表';
ALTER TABLE ACT_RU_TIMER_JOB COMMENT = '定时作业表';
ALTER TABLE ACT_RU_VARIABLE COMMENT = '运行时变量表';
ALTER TABLE ACT_EVT_LOG COMMENT = '事件日志表';
ALTER TABLE ACT_PROCDEF_INFO COMMENT = '流程定义信息';

ALTER TABLE ACT_GE_BYTEARRAY MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_GE_BYTEARRAY MODIFY COLUMN REV_ INTEGER COMMENT '数据版本';
ALTER TABLE ACT_GE_BYTEARRAY MODIFY COLUMN NAME_ NVARCHAR2(255) COMMENT '资源名称';
ALTER TABLE ACT_GE_BYTEARRAY MODIFY COLUMN DEPLOYMENT_ID_ NVARCHAR2(64) COMMENT '部署序号';
ALTER TABLE ACT_GE_BYTEARRAY MODIFY COLUMN BYTES_ BLOB COMMENT '资源内容';
ALTER TABLE ACT_GE_BYTEARRAY MODIFY COLUMN GENERATED_ NUMBER(1) COMMENT '是否是右 activiti 自动产生的资源';


ALTER TABLE ACT_GE_PROPERTY MODIFY COLUMN NAME_ NVARCHAR2(64) NOT NULL COMMENT '属性名称';
ALTER TABLE ACT_GE_PROPERTY MODIFY COLUMN VALUE_ NVARCHAR2(300) COMMENT '属性值';
ALTER TABLE ACT_GE_PROPERTY MODIFY COLUMN REV_ INTEGER COMMENT '数据版本号';


ALTER TABLE ACT_RE_DEPLOYMENT MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '部署序号';
ALTER TABLE ACT_RE_DEPLOYMENT MODIFY COLUMN NAME_ NVARCHAR2(255) COMMENT '部署名称';
ALTER TABLE ACT_RE_DEPLOYMENT MODIFY COLUMN CATEGORY_ NVARCHAR2(255) COMMENT '类别';
ALTER TABLE ACT_RE_DEPLOYMENT MODIFY COLUMN KEY_ NVARCHAR2(255) COMMENT '流程定义 ID';
ALTER TABLE ACT_RE_DEPLOYMENT MODIFY COLUMN TENANT_ID_ NVARCHAR2(255) COMMENT '租户id';
ALTER TABLE ACT_RE_DEPLOYMENT MODIFY COLUMN DEPLOY_TIME_ TIMESTAMP(6) COMMENT '部署时间';
ALTER TABLE ACT_RE_DEPLOYMENT MODIFY COLUMN ENGINE_VERSION_ NVARCHAR2(255) COMMENT '引擎版本';


ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN REV_ INTEGER COMMENT '数据版本号';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN CATEGORY_ NVARCHAR2(255) COMMENT '流程定义分类';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN NAME_ NVARCHAR2(255) COMMENT '流程定义的名称';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN KEY_ NVARCHAR2(255) COMMENT '流程定义 key';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN VERSION_ INTEGER COMMENT '版本';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN DEPLOYMENT_ID_ NVARCHAR2(64) COMMENT '部署 ID';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN RESOURCE_NAME_ NVARCHAR2(2000) COMMENT 'bpmn 文件名称';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN DGRM_RESOURCE_NAME_ VARCHAR2(4000) COMMENT '流程定义对应的流程图资源名称';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN DESCRIPTION_ NVARCHAR2(2000) COMMENT '说明';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN HAS_START_FORM_KEY_ NUMBER(1) COMMENT '是否存在开始节点 formKey';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN HAS_GRAPHICAL_NOTATION_ NUMBER(1) COMMENT '';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN SUSPENSION_STATE_ INTEGER COMMENT '流程定义状态';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN TENANT_ID_ NVARCHAR2(255) COMMENT '租户id';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN ENGINE_VERSION_ NVARCHAR2(255) COMMENT '引擎版本';


ALTER TABLE ACT_ID_USER MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_ID_USER MODIFY COLUMN REV_ INTEGER COMMENT '数据版本';
ALTER TABLE ACT_ID_USER MODIFY COLUMN FIRST_ NVARCHAR2(255) COMMENT '人名';
ALTER TABLE ACT_ID_USER MODIFY COLUMN LAST_ NVARCHAR2(255) COMMENT '姓氏';
ALTER TABLE ACT_ID_USER MODIFY COLUMN EMAIL_ NVARCHAR2(255) COMMENT '邮件';
ALTER TABLE ACT_ID_USER MODIFY COLUMN PWD_ NVARCHAR2(255) COMMENT '用户密码';
ALTER TABLE ACT_ID_USER MODIFY COLUMN PICTURE_ID_ NVARCHAR2(64) COMMENT '图片 ID';


ALTER TABLE ACT_ID_INFO MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_ID_INFO MODIFY COLUMN REV_ INTEGER COMMENT '数据版本';
ALTER TABLE ACT_ID_INFO MODIFY COLUMN USER_ID_ NVARCHAR2(64) COMMENT '对应用户表主键';
ALTER TABLE ACT_ID_INFO MODIFY COLUMN TYPE_ NVARCHAR2(64) COMMENT '信息类型';
ALTER TABLE ACT_ID_INFO MODIFY COLUMN KEY_ NVARCHAR2(255) COMMENT '数据的键';
ALTER TABLE ACT_ID_INFO MODIFY COLUMN VALUE_ NVARCHAR2(255) COMMENT '数据的值';
ALTER TABLE ACT_ID_INFO MODIFY COLUMN PASSWORD_ BLOB COMMENT '用户密码';
ALTER TABLE ACT_ID_INFO MODIFY COLUMN PARENT_ID_ NVARCHAR2(255) COMMENT '父信息 ID';


ALTER TABLE ACT_ID_GROUP MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_ID_GROUP MODIFY COLUMN REV_ INTEGER COMMENT '数据版本';
ALTER TABLE ACT_ID_GROUP MODIFY COLUMN NAME_ NVARCHAR2(255) COMMENT '用户组名称';
ALTER TABLE ACT_ID_GROUP MODIFY COLUMN TYPE_ NVARCHAR2(255) COMMENT '用户组类型';


ALTER TABLE ACT_ID_MEMBERSHIP MODIFY COLUMN USER_ID_ NVARCHAR2(64) NOT NULL COMMENT '用户 ID';
ALTER TABLE ACT_ID_MEMBERSHIP MODIFY COLUMN GROUP_ID_ NVARCHAR2(64) NOT NULL COMMENT '用户组 ID';


ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN REV_ INTEGER COMMENT '数据版本';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN PROC_INST_ID_ NVARCHAR2(64) COMMENT '流程实例 ID';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN BUSINESS_KEY_ NVARCHAR2(255) COMMENT '业务主键 ID';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN PARENT_ID_ NVARCHAR2(64) COMMENT '父执行流的 ID';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN PROC_DEF_ID_ NVARCHAR2(64) COMMENT '流程定义的数据 ID';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN SUPER_EXEC_ NVARCHAR2(64) COMMENT '';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN ROOT_PROC_INST_ID_ NVARCHAR2(64) COMMENT '';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN ACT_ID_ NVARCHAR2(255) COMMENT '节点实例 ID';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN IS_ACTIVE_ NUMBER(1) COMMENT '是否存活';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN IS_CONCURRENT_ NUMBER(1) COMMENT '执行流是否正在并行';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN IS_SCOPE_ NUMBER(1) COMMENT '';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN IS_EVENT_SCOPE_ NUMBER(1) COMMENT '';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN IS_MI_ROOT_ NUMBER(1) COMMENT '';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN SUSPENSION_STATE_ INTEGER COMMENT '流程终端状态';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN CACHED_ENT_STATE_ INTEGER COMMENT '';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN TENANT_ID_ NVARCHAR2(255) COMMENT '租户id';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN NAME_ NVARCHAR2(255) COMMENT '';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN START_TIME_ TIMESTAMP(6) COMMENT '开始时间';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN START_USER_ID_ NVARCHAR2(255) COMMENT '';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN LOCK_TIME_ TIMESTAMP(6) COMMENT '';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN IS_COUNT_ENABLED_ NUMBER(1) COMMENT '';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN EVT_SUBSCR_COUNT_ INTEGER COMMENT '';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN TASK_COUNT_ INTEGER COMMENT '';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN JOB_COUNT_ INTEGER COMMENT '';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN TIMER_JOB_COUNT_ INTEGER COMMENT '';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN SUSP_JOB_COUNT_ INTEGER COMMENT '';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN DEADLETTER_JOB_COUNT_ INTEGER COMMENT '';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN VAR_COUNT_ INTEGER COMMENT '';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN ID_LINK_COUNT_ INTEGER COMMENT '';


ALTER TABLE ACT_RU_TASK MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN REV_ INTEGER COMMENT '数据版本';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN EXECUTION_ID_ NVARCHAR2(64) COMMENT '任务所在的执行流 ID';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN PROC_INST_ID_ NVARCHAR2(64) COMMENT '流程实例 ID';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN PROC_DEF_ID_ NVARCHAR2(64) COMMENT '流程定义数据 ID';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN NAME_ NVARCHAR2(255) COMMENT '任务名称';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN PARENT_TASK_ID_ NVARCHAR2(64) COMMENT '父任务 ID';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN DESCRIPTION_ NVARCHAR2(2000) COMMENT '说明';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN TASK_DEF_KEY_ NVARCHAR2(255) COMMENT '任务定义的 ID 值';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN OWNER_ NVARCHAR2(255) COMMENT '任务拥有人';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN ASSIGNEE_ NVARCHAR2(255) COMMENT '被指派执行该任务的人';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN DELEGATION_ NVARCHAR2(64) COMMENT '';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN PRIORITY_ INTEGER COMMENT '';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN CREATE_TIME_ TIMESTAMP(6) COMMENT '创建时间';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN DUE_DATE_ TIMESTAMP(6) COMMENT '耗时';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN CATEGORY_ NVARCHAR2(255) COMMENT '';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN SUSPENSION_STATE_ INTEGER COMMENT '是否挂起';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN TENANT_ID_ NVARCHAR2(255) COMMENT '租户id';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN FORM_KEY_ NVARCHAR2(255) COMMENT '';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN CLAIM_TIME_ TIMESTAMP(6) COMMENT '';


ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN REV_ INTEGER COMMENT '数据版本';
ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN TYPE_ NVARCHAR2(255) COMMENT '参数类型';
ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN NAME_ NVARCHAR2(255) COMMENT '参数名称';
ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN EXECUTION_ID_ NVARCHAR2(64) COMMENT '参数执行 ID';
ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN PROC_INST_ID_ NVARCHAR2(64) COMMENT '流程实例 ID';
ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN TASK_ID_ NVARCHAR2(64) COMMENT '任务 ID';
ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN BYTEARRAY_ID_ NVARCHAR2(64) COMMENT '资源 ID';
ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN DOUBLE_ NUMBER(*,10) COMMENT '参数为 double，则保存在该字段中';
ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN LONG_ NUMBER(19) COMMENT '参数为 long，则保存在该字段中';
ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN TEXT_ NVARCHAR2(2000) COMMENT '用户保存文本类型的参数值';
ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN TEXT2_ NVARCHAR2(2000) COMMENT '用户保存文本类型的参数值';


ALTER TABLE ACT_RU_IDENTITYLINK MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_RU_IDENTITYLINK MODIFY COLUMN REV_ INTEGER COMMENT '数据版本';
ALTER TABLE ACT_RU_IDENTITYLINK MODIFY COLUMN GROUP_ID_ NVARCHAR2(255) COMMENT '用户组 ID';
ALTER TABLE ACT_RU_IDENTITYLINK MODIFY COLUMN TYPE_ NVARCHAR2(255) COMMENT '关系数据类型';
ALTER TABLE ACT_RU_IDENTITYLINK MODIFY COLUMN USER_ID_ NVARCHAR2(255) COMMENT '用户 ID';
ALTER TABLE ACT_RU_IDENTITYLINK MODIFY COLUMN TASK_ID_ NVARCHAR2(64) COMMENT '任务 ID';
ALTER TABLE ACT_RU_IDENTITYLINK MODIFY COLUMN PROC_INST_ID_ NVARCHAR2(64) COMMENT '流程定义 ID';
ALTER TABLE ACT_RU_IDENTITYLINK MODIFY COLUMN PROC_DEF_ID_ NVARCHAR2(64) COMMENT '属性 ID';


ALTER TABLE ACT_RU_JOB MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_RU_JOB MODIFY COLUMN REV_ INTEGER COMMENT '数据版本';
ALTER TABLE ACT_RU_JOB MODIFY COLUMN TYPE_ NVARCHAR2(255) COMMENT '类型';
ALTER TABLE ACT_RU_JOB MODIFY COLUMN LOCK_EXP_TIME_ TIMESTAMP(6) COMMENT '锁定释放时间';
ALTER TABLE ACT_RU_JOB MODIFY COLUMN LOCK_OWNER_ NVARCHAR2(255) COMMENT '挂起者';
ALTER TABLE ACT_RU_JOB MODIFY COLUMN EXCLUSIVE_ NUMBER(1) COMMENT '';
ALTER TABLE ACT_RU_JOB MODIFY COLUMN EXECUTION_ID_ NVARCHAR2(64) COMMENT '执行实例 ID';
ALTER TABLE ACT_RU_JOB MODIFY COLUMN PROCESS_INSTANCE_ID_ NVARCHAR2(64) COMMENT '流程实例 ID';
ALTER TABLE ACT_RU_JOB MODIFY COLUMN PROC_DEF_ID_ NVARCHAR2(64) COMMENT '流程定义 ID';
ALTER TABLE ACT_RU_JOB MODIFY COLUMN RETRIES_ INTEGER COMMENT '';
ALTER TABLE ACT_RU_JOB MODIFY COLUMN EXCEPTION_STACK_ID_ NVARCHAR2(64) COMMENT '异常信息 ID';
ALTER TABLE ACT_RU_JOB MODIFY COLUMN EXCEPTION_MSG_ NVARCHAR2(2000) COMMENT '异常信息';
ALTER TABLE ACT_RU_JOB MODIFY COLUMN DUEDATE_ TIMESTAMP(6) COMMENT '到期时间';
ALTER TABLE ACT_RU_JOB MODIFY COLUMN REPEAT_ NVARCHAR2(255) COMMENT '重复';
ALTER TABLE ACT_RU_JOB MODIFY COLUMN HANDLER_TYPE_ NVARCHAR2(255) COMMENT '处理类型';
ALTER TABLE ACT_RU_JOB MODIFY COLUMN HANDLER_CFG_ NVARCHAR2(2000) COMMENT '';
ALTER TABLE ACT_RU_JOB MODIFY COLUMN TENANT_ID_ NVARCHAR2(255) COMMENT '租户id';


ALTER TABLE ACT_RU_DEADLETTER_JOB MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_RU_DEADLETTER_JOB MODIFY COLUMN REV_ INTEGER COMMENT '数据版本';
ALTER TABLE ACT_RU_DEADLETTER_JOB MODIFY COLUMN TYPE_ NVARCHAR2(255) COMMENT '类型';
ALTER TABLE ACT_RU_DEADLETTER_JOB MODIFY COLUMN EXCLUSIVE_ NUMBER(1) COMMENT '';
ALTER TABLE ACT_RU_DEADLETTER_JOB MODIFY COLUMN EXECUTION_ID_ NVARCHAR2(64) COMMENT '执行实例 ID';
ALTER TABLE ACT_RU_DEADLETTER_JOB MODIFY COLUMN PROCESS_INSTANCE_ID_ NVARCHAR2(64) COMMENT '流程实例 ID';
ALTER TABLE ACT_RU_DEADLETTER_JOB MODIFY COLUMN PROC_DEF_ID_ NVARCHAR2(64) COMMENT '流程定义 ID';
ALTER TABLE ACT_RU_DEADLETTER_JOB MODIFY COLUMN RETRIES_ INTEGER COMMENT '';
ALTER TABLE ACT_RU_DEADLETTER_JOB MODIFY COLUMN EXCEPTION_STACK_ID_ NVARCHAR2(64) COMMENT '异常信息 ID';
ALTER TABLE ACT_RU_DEADLETTER_JOB MODIFY COLUMN EXCEPTION_MSG_ NVARCHAR2(2000) COMMENT '异常信息';
ALTER TABLE ACT_RU_DEADLETTER_JOB MODIFY COLUMN DUEDATE_ TIMESTAMP(6) COMMENT '到期时间';
ALTER TABLE ACT_RU_DEADLETTER_JOB MODIFY COLUMN REPEAT_ NVARCHAR2(255) COMMENT '重复';
ALTER TABLE ACT_RU_DEADLETTER_JOB MODIFY COLUMN HANDLER_TYPE_ NVARCHAR2(255) COMMENT '处理类型';
ALTER TABLE ACT_RU_DEADLETTER_JOB MODIFY COLUMN HANDLER_CFG_ NVARCHAR2(2000) COMMENT '';
ALTER TABLE ACT_RU_DEADLETTER_JOB MODIFY COLUMN TENANT_ID_ NVARCHAR2(255) COMMENT '租户id';


ALTER TABLE ACT_RU_SUSPENDED_JOB MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_RU_SUSPENDED_JOB MODIFY COLUMN REV_ INTEGER COMMENT '数据版本';
ALTER TABLE ACT_RU_SUSPENDED_JOB MODIFY COLUMN TYPE_ NVARCHAR2(255) COMMENT '类型';
ALTER TABLE ACT_RU_SUSPENDED_JOB MODIFY COLUMN EXCLUSIVE_ NUMBER(1) COMMENT '';
ALTER TABLE ACT_RU_SUSPENDED_JOB MODIFY COLUMN EXECUTION_ID_ NVARCHAR2(64) COMMENT '执行实例 ID';
ALTER TABLE ACT_RU_SUSPENDED_JOB MODIFY COLUMN PROCESS_INSTANCE_ID_ NVARCHAR2(64) COMMENT '流程实例 ID';
ALTER TABLE ACT_RU_SUSPENDED_JOB MODIFY COLUMN PROC_DEF_ID_ NVARCHAR2(64) COMMENT '流程定义 ID';
ALTER TABLE ACT_RU_SUSPENDED_JOB MODIFY COLUMN RETRIES_ INTEGER COMMENT '';
ALTER TABLE ACT_RU_SUSPENDED_JOB MODIFY COLUMN EXCEPTION_STACK_ID_ NVARCHAR2(64) COMMENT '异常信息 ID';
ALTER TABLE ACT_RU_SUSPENDED_JOB MODIFY COLUMN EXCEPTION_MSG_ NVARCHAR2(2000) COMMENT '异常信息';
ALTER TABLE ACT_RU_SUSPENDED_JOB MODIFY COLUMN DUEDATE_ TIMESTAMP(6) COMMENT '到期时间';
ALTER TABLE ACT_RU_SUSPENDED_JOB MODIFY COLUMN REPEAT_ NVARCHAR2(255) COMMENT '重复';
ALTER TABLE ACT_RU_SUSPENDED_JOB MODIFY COLUMN HANDLER_TYPE_ NVARCHAR2(255) COMMENT '处理类型';
ALTER TABLE ACT_RU_SUSPENDED_JOB MODIFY COLUMN HANDLER_CFG_ NVARCHAR2(2000) COMMENT '';
ALTER TABLE ACT_RU_SUSPENDED_JOB MODIFY COLUMN TENANT_ID_ NVARCHAR2(255) COMMENT '租户id';


ALTER TABLE ACT_RU_TIMER_JOB MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_RU_TIMER_JOB MODIFY COLUMN REV_ INTEGER COMMENT '数据版本';
ALTER TABLE ACT_RU_TIMER_JOB MODIFY COLUMN TYPE_ NVARCHAR2(255) COMMENT '类型';
ALTER TABLE ACT_RU_TIMER_JOB MODIFY COLUMN EXCLUSIVE_ NUMBER(1) COMMENT '';
ALTER TABLE ACT_RU_TIMER_JOB MODIFY COLUMN EXECUTION_ID_ NVARCHAR2(64) COMMENT '执行实例 ID';
ALTER TABLE ACT_RU_TIMER_JOB MODIFY COLUMN PROCESS_INSTANCE_ID_ NVARCHAR2(64) COMMENT '流程实例 ID';
ALTER TABLE ACT_RU_TIMER_JOB MODIFY COLUMN PROC_DEF_ID_ NVARCHAR2(64) COMMENT '流程定义 ID';
ALTER TABLE ACT_RU_TIMER_JOB MODIFY COLUMN RETRIES_ INTEGER COMMENT '';
ALTER TABLE ACT_RU_TIMER_JOB MODIFY COLUMN EXCEPTION_STACK_ID_ NVARCHAR2(64) COMMENT '异常信息 ID';
ALTER TABLE ACT_RU_TIMER_JOB MODIFY COLUMN EXCEPTION_MSG_ NVARCHAR2(2000) COMMENT '异常信息';
ALTER TABLE ACT_RU_TIMER_JOB MODIFY COLUMN DUEDATE_ TIMESTAMP(6) COMMENT '到期时间';
ALTER TABLE ACT_RU_TIMER_JOB MODIFY COLUMN REPEAT_ NVARCHAR2(255) COMMENT '重复';
ALTER TABLE ACT_RU_TIMER_JOB MODIFY COLUMN HANDLER_TYPE_ NVARCHAR2(255) COMMENT '处理类型';
ALTER TABLE ACT_RU_TIMER_JOB MODIFY COLUMN HANDLER_CFG_ NVARCHAR2(2000) COMMENT '';
ALTER TABLE ACT_RU_TIMER_JOB MODIFY COLUMN TENANT_ID_ NVARCHAR2(255) COMMENT '租户id';


ALTER TABLE ACT_RU_EVENT_SUBSCR MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_RU_EVENT_SUBSCR MODIFY COLUMN REV_ INTEGER COMMENT '数据版本';
ALTER TABLE ACT_RU_EVENT_SUBSCR MODIFY COLUMN EVENT_TYPE_ NVARCHAR2(255) COMMENT '事件类型';
ALTER TABLE ACT_RU_EVENT_SUBSCR MODIFY COLUMN EVENT_NAME_ NVARCHAR2(255) COMMENT '事件名称';
ALTER TABLE ACT_RU_EVENT_SUBSCR MODIFY COLUMN EXECUTION_ID_ NVARCHAR2(64) COMMENT '指定 ID';
ALTER TABLE ACT_RU_EVENT_SUBSCR MODIFY COLUMN PROC_INST_ID_ NVARCHAR2(64) COMMENT '流程定义 ID';
ALTER TABLE ACT_RU_EVENT_SUBSCR MODIFY COLUMN ACTIVITY_ID_ NVARCHAR2(64) COMMENT '具体事件 ID';
ALTER TABLE ACT_RU_EVENT_SUBSCR MODIFY COLUMN CONFIGURATION_ NVARCHAR2(255) COMMENT '事件的配置属性';
ALTER TABLE ACT_RU_EVENT_SUBSCR MODIFY COLUMN CREATED_ TIMESTAMP(6) COMMENT '创建时间';
ALTER TABLE ACT_RU_EVENT_SUBSCR MODIFY COLUMN PROC_DEF_ID_ NVARCHAR2(64) COMMENT '属性 ID';
ALTER TABLE ACT_RU_EVENT_SUBSCR MODIFY COLUMN TENANT_ID_ NVARCHAR2(255) COMMENT '租户id';


ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN PROC_INST_ID_ NVARCHAR2(64) COMMENT '流程实例 ID';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN BUSINESS_KEY_ NVARCHAR2(255) COMMENT '业务主键';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN PROC_DEF_ID_ NVARCHAR2(64) COMMENT '属性 ID';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN START_TIME_ TIMESTAMP(6) COMMENT '开始时间';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN END_TIME_ TIMESTAMP(6) COMMENT '结束时间';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN DURATION_ NUMBER(19) COMMENT '耗时';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN START_USER_ID_ NVARCHAR2(255) COMMENT '起始人';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN START_ACT_ID_ NVARCHAR2(255) COMMENT '起始节点';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN END_ACT_ID_ NVARCHAR2(255) COMMENT '结束节点';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN SUPER_PROCESS_INSTANCE_ID_ NVARCHAR2(64) COMMENT '父流程实例 ID';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN DELETE_REASON_ NVARCHAR2(2000) COMMENT '删除原因';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN TENANT_ID_ NVARCHAR2(255) COMMENT '租户id';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN NAME_ NVARCHAR2(255) COMMENT '名称';


ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN REV_ INTEGER COMMENT '数据版本';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN TYPE_ NVARCHAR2(255) COMMENT '类型';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN PROC_INST_ID_ NVARCHAR2(64) COMMENT '流程实例 ID';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN EXECUTION_ID_ NVARCHAR2(64) COMMENT '执行 ID';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN TASK_ID_ NVARCHAR2(64) COMMENT '任务 ID';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN ACT_INST_ID_ NVARCHAR2(64) COMMENT '节点实例 ID';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN NAME_ NVARCHAR2(255) COMMENT '名称';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN VAR_TYPE_ NVARCHAR2(64) COMMENT '参数类型';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN TIME_ TIMESTAMP(6) COMMENT '时间戳';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN BYTEARRAY_ID_ NVARCHAR2(64) COMMENT '字节表 ID';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN DOUBLE_ NUMBER(*,10) COMMENT '存储变量类型为 Double';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN LONG_ NUMBER(19) COMMENT '存储变量类型为 long';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN TEXT_ NVARCHAR2(2000) COMMENT '存储变量值类型为 String';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN TEXT2_ NVARCHAR2(2000) COMMENT '此处存储的是 JPA 持久化对象时，才会有值。此值为对象 ID';


ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN PROC_DEF_ID_ NVARCHAR2(64) COMMENT '流程定义 ID';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN TASK_DEF_KEY_ NVARCHAR2(255) COMMENT '任务定义的 ID 值';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN PROC_INST_ID_ NVARCHAR2(64) COMMENT '流程实例 ID';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN EXECUTION_ID_ NVARCHAR2(64) COMMENT '执行 ID';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN PARENT_TASK_ID_ NVARCHAR2(64) COMMENT '父任务 ID';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN NAME_ NVARCHAR2(255) COMMENT '名称';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN DESCRIPTION_ NVARCHAR2(2000) COMMENT '说明';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN OWNER_ NVARCHAR2(255) COMMENT '实际签收人 任务的拥有者';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN ASSIGNEE_ NVARCHAR2(255) COMMENT '被指派执行该任务的人';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN START_TIME_ TIMESTAMP(6) COMMENT '开始时间';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN CLAIM_TIME_ TIMESTAMP(6) COMMENT '提醒时间';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN END_TIME_ TIMESTAMP(6) COMMENT '结束时间';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN DURATION_ NUMBER(19) COMMENT '耗时';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN DELETE_REASON_ NVARCHAR2(2000) COMMENT '删除原因';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN PRIORITY_ INTEGER COMMENT '优先级别';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN DUE_DATE_ TIMESTAMP(6) COMMENT '过期时间';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN FORM_KEY_ NVARCHAR2(255) COMMENT '节点定义的 formkey';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN CATEGORY_ NVARCHAR2(255) COMMENT '类别';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN TENANT_ID_ NVARCHAR2(255) COMMENT '租户id';


ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN PROC_DEF_ID_ NVARCHAR2(64) COMMENT '流程定义 ID';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN PROC_INST_ID_ NVARCHAR2(64) COMMENT '流程实例 ID';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN EXECUTION_ID_ NVARCHAR2(64) COMMENT '执行 ID';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN ACT_ID_ NVARCHAR2(255) COMMENT '节点实例 ID';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN TASK_ID_ NVARCHAR2(64) COMMENT '任务 ID';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN CALL_PROC_INST_ID_ NVARCHAR2(64) COMMENT '调用外部的流程实例 ID';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN ACT_NAME_ NVARCHAR2(255) COMMENT '节点名称';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN ACT_TYPE_ NVARCHAR2(255) COMMENT '节点类型';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN ASSIGNEE_ NVARCHAR2(255) COMMENT '节点签收人';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN START_TIME_ TIMESTAMP(6) COMMENT '开始时间';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN END_TIME_ TIMESTAMP(6) COMMENT '结束时间';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN DURATION_ NUMBER(19) COMMENT '耗时';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN DELETE_REASON_ NVARCHAR2(2000) COMMENT '删除原因';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN TENANT_ID_ NVARCHAR2(255) COMMENT '租户id';


ALTER TABLE ACT_HI_ATTACHMENT MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_HI_ATTACHMENT MODIFY COLUMN REV_ INTEGER COMMENT '数据版本';
ALTER TABLE ACT_HI_ATTACHMENT MODIFY COLUMN USER_ID_ NVARCHAR2(255) COMMENT '用户 ID';
ALTER TABLE ACT_HI_ATTACHMENT MODIFY COLUMN NAME_ NVARCHAR2(255) COMMENT '名称';
ALTER TABLE ACT_HI_ATTACHMENT MODIFY COLUMN DESCRIPTION_ NVARCHAR2(2000) COMMENT '说明';
ALTER TABLE ACT_HI_ATTACHMENT MODIFY COLUMN TYPE_ NVARCHAR2(255) COMMENT '类型';
ALTER TABLE ACT_HI_ATTACHMENT MODIFY COLUMN TASK_ID_ NVARCHAR2(64) COMMENT '任务 ID';
ALTER TABLE ACT_HI_ATTACHMENT MODIFY COLUMN PROC_INST_ID_ NVARCHAR2(64) COMMENT '流程实例 ID';
ALTER TABLE ACT_HI_ATTACHMENT MODIFY COLUMN URL_ NVARCHAR2(2000) COMMENT '';
ALTER TABLE ACT_HI_ATTACHMENT MODIFY COLUMN CONTENT_ID_ NVARCHAR2(64) COMMENT '字节表的 ID';
ALTER TABLE ACT_HI_ATTACHMENT MODIFY COLUMN TIME_ TIMESTAMP(6) COMMENT '时间';


ALTER TABLE ACT_HI_COMMENT MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_HI_COMMENT MODIFY COLUMN TYPE_ NVARCHAR2(255) COMMENT '类型';
ALTER TABLE ACT_HI_COMMENT MODIFY COLUMN TIME_ TIMESTAMP(6) COMMENT '时间';
ALTER TABLE ACT_HI_COMMENT MODIFY COLUMN USER_ID_ NVARCHAR2(255) COMMENT '用户 ID';
ALTER TABLE ACT_HI_COMMENT MODIFY COLUMN TASK_ID_ NVARCHAR2(64) COMMENT '任务 ID';
ALTER TABLE ACT_HI_COMMENT MODIFY COLUMN PROC_INST_ID_ NVARCHAR2(64) COMMENT '流程实例 ID';
ALTER TABLE ACT_HI_COMMENT MODIFY COLUMN ACTION_ NVARCHAR2(255) COMMENT '行为类型';
ALTER TABLE ACT_HI_COMMENT MODIFY COLUMN MESSAGE_ NVARCHAR2(2000) COMMENT '信息';
ALTER TABLE ACT_HI_COMMENT MODIFY COLUMN FULL_MSG_ BLOB COMMENT '全部内容';


ALTER TABLE ACT_RE_MODEL MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_RE_MODEL MODIFY COLUMN REV_ INTEGER COMMENT '数据版本';
ALTER TABLE ACT_RE_MODEL MODIFY COLUMN NAME_ NVARCHAR2(255) COMMENT '';
ALTER TABLE ACT_RE_MODEL MODIFY COLUMN KEY_ NVARCHAR2(255) COMMENT '';
ALTER TABLE ACT_RE_MODEL MODIFY COLUMN CATEGORY_ NVARCHAR2(255) COMMENT '分类';
ALTER TABLE ACT_RE_MODEL MODIFY COLUMN CREATE_TIME_ TIMESTAMP(6) COMMENT '创建时间';
ALTER TABLE ACT_RE_MODEL MODIFY COLUMN LAST_UPDATE_TIME_ TIMESTAMP(6) COMMENT '最后更新时间';
ALTER TABLE ACT_RE_MODEL MODIFY COLUMN VERSION_ INTEGER COMMENT '版本';
ALTER TABLE ACT_RE_MODEL MODIFY COLUMN META_INFO_ NVARCHAR2(2000) COMMENT '以 json 格式保存流程定义的信息';
ALTER TABLE ACT_RE_MODEL MODIFY COLUMN DEPLOYMENT_ID_ NVARCHAR2(64) COMMENT '部署 ID';
ALTER TABLE ACT_RE_MODEL MODIFY COLUMN EDITOR_SOURCE_VALUE_ID_ NVARCHAR2(64) COMMENT '';
ALTER TABLE ACT_RE_MODEL MODIFY COLUMN EDITOR_SOURCE_EXTRA_VALUE_ID_ NVARCHAR2(64) COMMENT '';
ALTER TABLE ACT_RE_MODEL MODIFY COLUMN TENANT_ID_ NVARCHAR2(255) COMMENT '租户id';


ALTER TABLE ACT_EVT_LOG MODIFY COLUMN LOG_NR_ NUMBER(19) NOT NULL COMMENT '主键';
ALTER TABLE ACT_EVT_LOG MODIFY COLUMN TYPE_ NVARCHAR2(64) COMMENT '类型';
ALTER TABLE ACT_EVT_LOG MODIFY COLUMN PROC_DEF_ID_ NVARCHAR2(64) COMMENT '流程定义 ID';
ALTER TABLE ACT_EVT_LOG MODIFY COLUMN PROC_INST_ID_ NVARCHAR2(64) COMMENT '流程实例 ID';
ALTER TABLE ACT_EVT_LOG MODIFY COLUMN EXECUTION_ID_ NVARCHAR2(64) COMMENT '执行 ID';
ALTER TABLE ACT_EVT_LOG MODIFY COLUMN TASK_ID_ NVARCHAR2(64) COMMENT '任务 ID';
ALTER TABLE ACT_EVT_LOG MODIFY COLUMN TIME_STAMP_ TIMESTAMP(6) COMMENT '';
ALTER TABLE ACT_EVT_LOG MODIFY COLUMN USER_ID_ NVARCHAR2(255) COMMENT '';
ALTER TABLE ACT_EVT_LOG MODIFY COLUMN DATA_ BLOB COMMENT '';
ALTER TABLE ACT_EVT_LOG MODIFY COLUMN LOCK_OWNER_ NVARCHAR2(255) COMMENT '';
ALTER TABLE ACT_EVT_LOG MODIFY COLUMN LOCK_TIME_ TIMESTAMP(6) COMMENT '';
ALTER TABLE ACT_EVT_LOG MODIFY COLUMN IS_PROCESSED_ NUMBER(3) COMMENT '';


ALTER TABLE ACT_PROCDEF_INFO MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_PROCDEF_INFO MODIFY COLUMN PROC_DEF_ID_ NVARCHAR2(64) COMMENT '流程定义 ID';
ALTER TABLE ACT_PROCDEF_INFO MODIFY COLUMN REV_ INTEGER COMMENT '数据版本';
ALTER TABLE ACT_PROCDEF_INFO MODIFY COLUMN INFO_JSON_ID_ NVARCHAR2(64) COMMENT '';


ALTER TABLE ACT_HI_VARINST MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN PROC_INST_ID_ NVARCHAR2(64) COMMENT '流程实例 ID';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN EXECUTION_ID_ NVARCHAR2(64) COMMENT '指定 ID';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN TASK_ID_ NVARCHAR2(64) COMMENT '任务 ID';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN NAME_ NVARCHAR2(255) COMMENT '名称';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN VAR_TYPE_ NVARCHAR2(100) COMMENT '参数类型';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN REV_ INTEGER COMMENT '数据版本';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN BYTEARRAY_ID_ NVARCHAR2(64) COMMENT '字节表 ID';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN DOUBLE_ NUMBER(*,10) COMMENT '存储 double 类型数据';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN LONG_ NUMBER(*,10) COMMENT '存储 long 类型数据';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN TEXT_ NVARCHAR2(2000) COMMENT '';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN TEXT2_ NVARCHAR2(2000) COMMENT '';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN CREATE_TIME_ TIMESTAMP(6)(2000) COMMENT '';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN LAST_UPDATED_TIME_ TIMESTAMP(6)(2000) COMMENT '';


ALTER TABLE ACT_HI_IDENTITYLINK MODIFY COLUMN ID_ NVARCHAR2(64) NOT NULL COMMENT '主键';
ALTER TABLE ACT_HI_IDENTITYLINK MODIFY COLUMN GROUP_ID_ NVARCHAR2(255) COMMENT '组 ID';
ALTER TABLE ACT_HI_IDENTITYLINK MODIFY COLUMN TYPE_ NVARCHAR2(255) COMMENT '类型';
ALTER TABLE ACT_HI_IDENTITYLINK MODIFY COLUMN USER_ID_ NVARCHAR2(255) COMMENT '用户 ID';
ALTER TABLE ACT_HI_IDENTITYLINK MODIFY COLUMN TASK_ID_ NVARCHAR2(64) COMMENT '任务 ID';
ALTER TABLE ACT_HI_IDENTITYLINK MODIFY COLUMN PROC_INST_ID_ NVARCHAR2(64) COMMENT '流程实例 ID';
