@startuml
DRAFT --> DRAFT : INIT
DRAFT --> PENDING_REVIEW : SUBMIT_FOR_REVIEW
REVOKED --> PENDING_REVIEW : SUBMIT_FOR_REVIEW
REJECTED --> PENDING_REVIEW : SUBMIT_FOR_REVIEW
PENDING_REVIEW --> REJECTED : REJECT
PENDING_REVIEW --> APPROVED : AGREE
APPROVED --> REVOKED : WITHDRAW_REVIEW
@enduml