@startuml
DRAFT --> DRAFT : INIT
DRAFT --> PROCESS : SUBMIT_FOR_REVIEW
PROCESS --> REJECTED : REJECT
REVERSED --> PROCESS : SUBMIT_FOR_REVIEW
APPROVE --> REVERSED : WITHDRAW_REVIEW
PROCESS --> APPROVE : AGREE
REJECTED --> APPROVE : AGREE
@enduml