### 请求 /erp/sale-statistics/summary 接口 => 成功
GET {{baseUrl}}/erp/sale-statistics/summary
Content-Type: application/json
tenant-id: {{adminTenentId}}
Authorization: Bearer {{token}}

### 请求 /erp/sale-statistics/time-summary 接口 => 成功
GET {{baseUrl}}/erp/sale-statistics/time-summary
Content-Type: application/json
tenant-id: {{adminTenentId}}
Authorization: Bearer {{token}}
