### 请求 /login 接口 => 成功
POST {{userServerUrl}}/login
Content-Type: application/json

{
  "mobile": "15601691300",
  "password": "admin123"
}

### 请求 /send-sms-code 接口 => 成功
POST {{userServerUrl}}/send-sms-code
Content-Type: application/json

{
  "mobile": "15601691300",
  "scene": 1
}
