
### chat call
POST {{baseUrl}}/admin-api/ai/chat/message/send
Content-Type: application/json
Authorization: {{token}}

{
  "conversationId": "1781604279872581649",
  "content": "你是 OpenAI 么？"
}


### 发送消息（流式）
POST {{baseUrl}}/ai/chat/message/send-stream
Content-Type: application/json
Authorization: {{token}}

{
  "conversationId": "1781604279872581690",
  "content": "1+1=?"
}

### message list
GET {{baseUrl}}/admin-api/ai/chat/message/list-by-conversation-id?conversationId=1781604279872581649
Authorization: {{token}}


### message delete
DELETE {{baseUrl}}/admin-api/ai/chat/message/delete?id=50
Authorization: {{token}}
