### 请求 /system/social-client/send-subscribe-message 接口 => 发送测试订阅消息
POST {{baseUrl}}/system/social-client/send-subscribe-message
Authorization: Bearer {{token}}
Content-Type: application/json
#Authorization: Bearer test100
tenant-id: {{adminTenentId}}

{
  "toUser": "oKNkb4xxw2H135-MVPKtEMkumK08",
  "templateId": "W4ybDTIwCfKHtMKR7fSfx83DtmVKEeXQo3Ti7GCw4_4",
  "miniprogramState": "developer",
  "lang": "zh_CN",
  "messages": {
     "character_string1":"5616122165165",
     "amount2":"1000.00",
     "time3":"2024-01-01 10:10:10",
     "phrase4":"成功"
  }
}
