/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.somle.tiktok.sdk.model.Product.V202309;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.somle.tiktok.sdk.invoke.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * ActivateProductResponseDataErrorsDetailExtraErrors
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-12T06:25:14.052506Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class ActivateProductResponseDataErrorsDetailExtraErrors {
    public static final String SERIALIZED_NAME_CODE = "code";
    public static final String SERIALIZED_NAME_MESSAGE = "message";
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("code");
        openapiFields.add("message");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    @SerializedName(SERIALIZED_NAME_CODE)
    private Integer code;
    @SerializedName(SERIALIZED_NAME_MESSAGE)
    private String message;

    public ActivateProductResponseDataErrorsDetailExtraErrors() {
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to ActivateProductResponseDataErrorsDetailExtraErrors
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!ActivateProductResponseDataErrorsDetailExtraErrors.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format("The required field(s) %s in ActivateProductResponseDataErrorsDetailExtraErrors is not found in the empty JSON string", ActivateProductResponseDataErrorsDetailExtraErrors.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!ActivateProductResponseDataErrorsDetailExtraErrors.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ActivateProductResponseDataErrorsDetailExtraErrors` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
        }
    }

    /**
     * Create an instance of ActivateProductResponseDataErrorsDetailExtraErrors given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of ActivateProductResponseDataErrorsDetailExtraErrors
     * @throws IOException if the JSON string is invalid with respect to ActivateProductResponseDataErrorsDetailExtraErrors
     */
    public static ActivateProductResponseDataErrorsDetailExtraErrors fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, ActivateProductResponseDataErrorsDetailExtraErrors.class);
    }

    public ActivateProductResponseDataErrorsDetailExtraErrors code(Integer code) {
        this.code = code;
        return this;
    }

    /**
     * The secondary error code.
     *
     * @return code
     **/
    @javax.annotation.Nullable
    public Integer getCode() {
        return code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }

    public ActivateProductResponseDataErrorsDetailExtraErrors message(String message) {
        this.message = message;
        return this;
    }

    /**
     * The secondary error message.
     *
     * @return message
     **/
    @javax.annotation.Nullable
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ActivateProductResponseDataErrorsDetailExtraErrors product202309ActivateProductResponseDataErrorsDetailExtraErrors = (ActivateProductResponseDataErrorsDetailExtraErrors) o;
        return Objects.equals(this.code, product202309ActivateProductResponseDataErrorsDetailExtraErrors.code) &&
            Objects.equals(this.message, product202309ActivateProductResponseDataErrorsDetailExtraErrors.message);
    }

    @Override
    public int hashCode() {
        return Objects.hash(code, message);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ActivateProductResponseDataErrorsDetailExtraErrors {\n");
        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert an instance of ActivateProductResponseDataErrorsDetailExtraErrors to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ActivateProductResponseDataErrorsDetailExtraErrors.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ActivateProductResponseDataErrorsDetailExtraErrors' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ActivateProductResponseDataErrorsDetailExtraErrors> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(ActivateProductResponseDataErrorsDetailExtraErrors.class));

            return (TypeAdapter<T>) new TypeAdapter<ActivateProductResponseDataErrorsDetailExtraErrors>() {
                @Override
                public void write(JsonWriter out, ActivateProductResponseDataErrorsDetailExtraErrors value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public ActivateProductResponseDataErrorsDetailExtraErrors read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }
}

