/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.somle.tiktok.sdk.model.Product.V202309;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.somle.tiktok.sdk.invoke.JSON;

import java.io.IOException;
import java.util.*;

/**
 * CreateProductResponseData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-12T06:25:14.052506Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class CreateProductResponseData {
    public static final String SERIALIZED_NAME_PRODUCT_ID = "product_id";
    public static final String SERIALIZED_NAME_SKUS = "skus";
    public static final String SERIALIZED_NAME_WARNINGS = "warnings";
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("product_id");
        openapiFields.add("skus");
        openapiFields.add("warnings");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    @SerializedName(SERIALIZED_NAME_PRODUCT_ID)
    private String productId;
    @SerializedName(SERIALIZED_NAME_SKUS)
    private List<CreateProductResponseDataSkus> skus = new ArrayList<>();
    @SerializedName(SERIALIZED_NAME_WARNINGS)
    private List<CreateProductResponseDataWarnings> warnings = new ArrayList<>();

    public CreateProductResponseData() {
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to CreateProductResponseData
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!CreateProductResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format("The required field(s) %s in CreateProductResponseData is not found in the empty JSON string", CreateProductResponseData.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!CreateProductResponseData.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateProductResponseData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("product_id") != null && !jsonObj.get("product_id").isJsonNull()) && !jsonObj.get("product_id").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `product_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("product_id").toString()));
        }
        if (jsonObj.get("skus") != null && !jsonObj.get("skus").isJsonNull()) {
            JsonArray jsonArrayskus = jsonObj.getAsJsonArray("skus");
            if (jsonArrayskus != null) {
                // ensure the json data is an array
                if (!jsonObj.get("skus").isJsonArray()) {
                    throw new IllegalArgumentException(String.format("Expected the field `skus` to be an array in the JSON string but got `%s`", jsonObj.get("skus").toString()));
                }

                // validate the optional field `skus` (array)
                for (int i = 0; i < jsonArrayskus.size(); i++) {
                    CreateProductResponseDataSkus.validateJsonElement(jsonArrayskus.get(i));
                }
                ;
            }
        }
        if (jsonObj.get("warnings") != null && !jsonObj.get("warnings").isJsonNull()) {
            JsonArray jsonArraywarnings = jsonObj.getAsJsonArray("warnings");
            if (jsonArraywarnings != null) {
                // ensure the json data is an array
                if (!jsonObj.get("warnings").isJsonArray()) {
                    throw new IllegalArgumentException(String.format("Expected the field `warnings` to be an array in the JSON string but got `%s`", jsonObj.get("warnings").toString()));
                }

                // validate the optional field `warnings` (array)
                for (int i = 0; i < jsonArraywarnings.size(); i++) {
                    CreateProductResponseDataWarnings.validateJsonElement(jsonArraywarnings.get(i));
                }
                ;
            }
        }
    }

    /**
     * Create an instance of CreateProductResponseData given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of CreateProductResponseData
     * @throws IOException if the JSON string is invalid with respect to CreateProductResponseData
     */
    public static CreateProductResponseData fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, CreateProductResponseData.class);
    }

    public CreateProductResponseData productId(String productId) {
        this.productId = productId;
        return this;
    }

    /**
     * The product ID generated by TikTok Shop.
     *
     * @return productId
     **/
    @javax.annotation.Nullable
    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public CreateProductResponseData skus(List<CreateProductResponseDataSkus> skus) {
        this.skus = skus;
        return this;
    }

    public CreateProductResponseData addSkusItem(CreateProductResponseDataSkus skusItem) {
        if (this.skus == null) {
            this.skus = new ArrayList<>();
        }
        this.skus.add(skusItem);
        return this;
    }

    /**
     * A list of Stock Keeping Units (SKUs) used to identify distinct variants of the product.
     *
     * @return skus
     **/
    @javax.annotation.Nullable
    public List<CreateProductResponseDataSkus> getSkus() {
        return skus;
    }

    public void setSkus(List<CreateProductResponseDataSkus> skus) {
        this.skus = skus;
    }

    public CreateProductResponseData warnings(List<CreateProductResponseDataWarnings> warnings) {
        this.warnings = warnings;
        return this;
    }

    public CreateProductResponseData addWarningsItem(CreateProductResponseDataWarnings warningsItem) {
        if (this.warnings == null) {
            this.warnings = new ArrayList<>();
        }
        this.warnings.add(warningsItem);
        return this;
    }

    /**
     * Warning information that the API caller needs to pay special attention to.
     *
     * @return warnings
     **/
    @javax.annotation.Nullable
    public List<CreateProductResponseDataWarnings> getWarnings() {
        return warnings;
    }

    public void setWarnings(List<CreateProductResponseDataWarnings> warnings) {
        this.warnings = warnings;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateProductResponseData product202309CreateProductResponseData = (CreateProductResponseData) o;
        return Objects.equals(this.productId, product202309CreateProductResponseData.productId) &&
            Objects.equals(this.skus, product202309CreateProductResponseData.skus) &&
            Objects.equals(this.warnings, product202309CreateProductResponseData.warnings);
    }

    @Override
    public int hashCode() {
        return Objects.hash(productId, skus, warnings);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreateProductResponseData {\n");
        sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
        sb.append("    skus: ").append(toIndentedString(skus)).append("\n");
        sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert an instance of CreateProductResponseData to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!CreateProductResponseData.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'CreateProductResponseData' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<CreateProductResponseData> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(CreateProductResponseData.class));

            return (TypeAdapter<T>) new TypeAdapter<CreateProductResponseData>() {
                @Override
                public void write(JsonWriter out, CreateProductResponseData value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public CreateProductResponseData read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }
}

