/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.somle.tiktok.sdk.model.Product.V202309;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.somle.tiktok.sdk.invoke.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * DeactivateProductsResponseDataErrors
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-12T06:25:14.052506Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class DeactivateProductsResponseDataErrors {
    public static final String SERIALIZED_NAME_CODE = "code";
    public static final String SERIALIZED_NAME_DETAIL = "detail";
    public static final String SERIALIZED_NAME_MESSAGE = "message";
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("code");
        openapiFields.add("detail");
        openapiFields.add("message");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    @SerializedName(SERIALIZED_NAME_CODE)
    private Integer code;
    @SerializedName(SERIALIZED_NAME_DETAIL)
    private DeactivateProductsResponseDataErrorsDetail detail;
    @SerializedName(SERIALIZED_NAME_MESSAGE)
    private String message;

    public DeactivateProductsResponseDataErrors() {
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to DeactivateProductsResponseDataErrors
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!DeactivateProductsResponseDataErrors.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format("The required field(s) %s in DeactivateProductsResponseDataErrors is not found in the empty JSON string", DeactivateProductsResponseDataErrors.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!DeactivateProductsResponseDataErrors.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DeactivateProductsResponseDataErrors` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // validate the optional field `detail`
        if (jsonObj.get("detail") != null && !jsonObj.get("detail").isJsonNull()) {
            DeactivateProductsResponseDataErrorsDetail.validateJsonElement(jsonObj.get("detail"));
        }
        if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
        }
    }

    /**
     * Create an instance of DeactivateProductsResponseDataErrors given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of DeactivateProductsResponseDataErrors
     * @throws IOException if the JSON string is invalid with respect to DeactivateProductsResponseDataErrors
     */
    public static DeactivateProductsResponseDataErrors fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, DeactivateProductsResponseDataErrors.class);
    }

    public DeactivateProductsResponseDataErrors code(Integer code) {
        this.code = code;
        return this;
    }

    /**
     * The main error code.
     *
     * @return code
     **/
    @javax.annotation.Nullable
    public Integer getCode() {
        return code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }

    public DeactivateProductsResponseDataErrors detail(DeactivateProductsResponseDataErrorsDetail detail) {
        this.detail = detail;
        return this;
    }

    /**
     * Get detail
     *
     * @return detail
     **/
    @javax.annotation.Nullable
    public DeactivateProductsResponseDataErrorsDetail getDetail() {
        return detail;
    }

    public void setDetail(DeactivateProductsResponseDataErrorsDetail detail) {
        this.detail = detail;
    }

    public DeactivateProductsResponseDataErrors message(String message) {
        this.message = message;
        return this;
    }

    /**
     * The main error message.
     *
     * @return message
     **/
    @javax.annotation.Nullable
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeactivateProductsResponseDataErrors product202309DeactivateProductsResponseDataErrors = (DeactivateProductsResponseDataErrors) o;
        return Objects.equals(this.code, product202309DeactivateProductsResponseDataErrors.code) &&
            Objects.equals(this.detail, product202309DeactivateProductsResponseDataErrors.detail) &&
            Objects.equals(this.message, product202309DeactivateProductsResponseDataErrors.message);
    }

    @Override
    public int hashCode() {
        return Objects.hash(code, detail, message);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DeactivateProductsResponseDataErrors {\n");
        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert an instance of DeactivateProductsResponseDataErrors to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!DeactivateProductsResponseDataErrors.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'DeactivateProductsResponseDataErrors' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<DeactivateProductsResponseDataErrors> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(DeactivateProductsResponseDataErrors.class));

            return (TypeAdapter<T>) new TypeAdapter<DeactivateProductsResponseDataErrors>() {
                @Override
                public void write(JsonWriter out, DeactivateProductsResponseDataErrors value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public DeactivateProductsResponseDataErrors read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }
}

