/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.somle.tiktok.sdk.model.Product.V202309;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.somle.tiktok.sdk.invoke.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * DeleteGlobalProductsResponseDataErrorsDetail
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-12T06:25:14.052506Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class DeleteGlobalProductsResponseDataErrorsDetail {
    public static final String SERIALIZED_NAME_GLOBAL_PRODUCT_ID = "global_product_id";
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("global_product_id");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    @SerializedName(SERIALIZED_NAME_GLOBAL_PRODUCT_ID)
    private String globalProductId;

    public DeleteGlobalProductsResponseDataErrorsDetail() {
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to DeleteGlobalProductsResponseDataErrorsDetail
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!DeleteGlobalProductsResponseDataErrorsDetail.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format("The required field(s) %s in DeleteGlobalProductsResponseDataErrorsDetail is not found in the empty JSON string", DeleteGlobalProductsResponseDataErrorsDetail.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!DeleteGlobalProductsResponseDataErrorsDetail.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DeleteGlobalProductsResponseDataErrorsDetail` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("global_product_id") != null && !jsonObj.get("global_product_id").isJsonNull()) && !jsonObj.get("global_product_id").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `global_product_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("global_product_id").toString()));
        }
    }

    /**
     * Create an instance of DeleteGlobalProductsResponseDataErrorsDetail given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of DeleteGlobalProductsResponseDataErrorsDetail
     * @throws IOException if the JSON string is invalid with respect to DeleteGlobalProductsResponseDataErrorsDetail
     */
    public static DeleteGlobalProductsResponseDataErrorsDetail fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, DeleteGlobalProductsResponseDataErrorsDetail.class);
    }

    public DeleteGlobalProductsResponseDataErrorsDetail globalProductId(String globalProductId) {
        this.globalProductId = globalProductId;
        return this;
    }

    /**
     * The ID of the global product that could not be deleted.
     *
     * @return globalProductId
     **/
    @javax.annotation.Nullable
    public String getGlobalProductId() {
        return globalProductId;
    }

    public void setGlobalProductId(String globalProductId) {
        this.globalProductId = globalProductId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeleteGlobalProductsResponseDataErrorsDetail product202309DeleteGlobalProductsResponseDataErrorsDetail = (DeleteGlobalProductsResponseDataErrorsDetail) o;
        return Objects.equals(this.globalProductId, product202309DeleteGlobalProductsResponseDataErrorsDetail.globalProductId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(globalProductId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DeleteGlobalProductsResponseDataErrorsDetail {\n");
        sb.append("    globalProductId: ").append(toIndentedString(globalProductId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert an instance of DeleteGlobalProductsResponseDataErrorsDetail to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!DeleteGlobalProductsResponseDataErrorsDetail.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'DeleteGlobalProductsResponseDataErrorsDetail' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<DeleteGlobalProductsResponseDataErrorsDetail> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(DeleteGlobalProductsResponseDataErrorsDetail.class));

            return (TypeAdapter<T>) new TypeAdapter<DeleteGlobalProductsResponseDataErrorsDetail>() {
                @Override
                public void write(JsonWriter out, DeleteGlobalProductsResponseDataErrorsDetail value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public DeleteGlobalProductsResponseDataErrorsDetail read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }
}

