/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.somle.tiktok.sdk.model.Product.V202309;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.somle.tiktok.sdk.invoke.JSON;

import java.io.IOException;
import java.util.*;

/**
 * EditGlobalProductRequestBodyCertifications
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-12T06:25:14.052506Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class EditGlobalProductRequestBodyCertifications {
    public static final String SERIALIZED_NAME_FILES = "files";
    public static final String SERIALIZED_NAME_ID = "id";
    public static final String SERIALIZED_NAME_IMAGES = "images";
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("files");
        openapiFields.add("id");
        openapiFields.add("images");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    @SerializedName(SERIALIZED_NAME_FILES)
    private List<EditGlobalProductRequestBodyCertificationsFiles> files = new ArrayList<>();
    @SerializedName(SERIALIZED_NAME_ID)
    private String id;
    @SerializedName(SERIALIZED_NAME_IMAGES)
    private List<EditGlobalProductRequestBodyCertificationsImages> images = new ArrayList<>();

    public EditGlobalProductRequestBodyCertifications() {
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to EditGlobalProductRequestBodyCertifications
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!EditGlobalProductRequestBodyCertifications.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format("The required field(s) %s in EditGlobalProductRequestBodyCertifications is not found in the empty JSON string", EditGlobalProductRequestBodyCertifications.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!EditGlobalProductRequestBodyCertifications.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EditGlobalProductRequestBodyCertifications` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (jsonObj.get("files") != null && !jsonObj.get("files").isJsonNull()) {
            JsonArray jsonArrayfiles = jsonObj.getAsJsonArray("files");
            if (jsonArrayfiles != null) {
                // ensure the json data is an array
                if (!jsonObj.get("files").isJsonArray()) {
                    throw new IllegalArgumentException(String.format("Expected the field `files` to be an array in the JSON string but got `%s`", jsonObj.get("files").toString()));
                }

                // validate the optional field `files` (array)
                for (int i = 0; i < jsonArrayfiles.size(); i++) {
                    EditGlobalProductRequestBodyCertificationsFiles.validateJsonElement(jsonArrayfiles.get(i));
                }
                ;
            }
        }
        if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
        }
        if (jsonObj.get("images") != null && !jsonObj.get("images").isJsonNull()) {
            JsonArray jsonArrayimages = jsonObj.getAsJsonArray("images");
            if (jsonArrayimages != null) {
                // ensure the json data is an array
                if (!jsonObj.get("images").isJsonArray()) {
                    throw new IllegalArgumentException(String.format("Expected the field `images` to be an array in the JSON string but got `%s`", jsonObj.get("images").toString()));
                }

                // validate the optional field `images` (array)
                for (int i = 0; i < jsonArrayimages.size(); i++) {
                    EditGlobalProductRequestBodyCertificationsImages.validateJsonElement(jsonArrayimages.get(i));
                }
                ;
            }
        }
    }

    /**
     * Create an instance of EditGlobalProductRequestBodyCertifications given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of EditGlobalProductRequestBodyCertifications
     * @throws IOException if the JSON string is invalid with respect to EditGlobalProductRequestBodyCertifications
     */
    public static EditGlobalProductRequestBodyCertifications fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, EditGlobalProductRequestBodyCertifications.class);
    }

    public EditGlobalProductRequestBodyCertifications files(List<EditGlobalProductRequestBodyCertificationsFiles> files) {
        this.files = files;
        return this;
    }

    public EditGlobalProductRequestBodyCertifications addFilesItem(EditGlobalProductRequestBodyCertificationsFiles filesItem) {
        if (this.files == null) {
            this.files = new ArrayList<>();
        }
        this.files.add(filesItem);
        return this;
    }

    /**
     * A list of certification related files.
     *
     * @return files
     **/
    @javax.annotation.Nullable
    public List<EditGlobalProductRequestBodyCertificationsFiles> getFiles() {
        return files;
    }

    public void setFiles(List<EditGlobalProductRequestBodyCertificationsFiles> files) {
        this.files = files;
    }

    public EditGlobalProductRequestBodyCertifications id(String id) {
        this.id = id;
        return this;
    }

    /**
     * The ID to identify the type of certification required for the product category. Retrieve this value from the [Get Global Category Rules API](https://partner.tiktokshop.com/docv2/page/650a056df1fd3102b91b5b8e).
     *
     * @return id
     **/
    @javax.annotation.Nullable
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public EditGlobalProductRequestBodyCertifications images(List<EditGlobalProductRequestBodyCertificationsImages> images) {
        this.images = images;
        return this;
    }

    public EditGlobalProductRequestBodyCertifications addImagesItem(EditGlobalProductRequestBodyCertificationsImages imagesItem) {
        if (this.images == null) {
            this.images = new ArrayList<>();
        }
        this.images.add(imagesItem);
        return this;
    }

    /**
     * A list of certification related images.
     *
     * @return images
     **/
    @javax.annotation.Nullable
    public List<EditGlobalProductRequestBodyCertificationsImages> getImages() {
        return images;
    }

    public void setImages(List<EditGlobalProductRequestBodyCertificationsImages> images) {
        this.images = images;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EditGlobalProductRequestBodyCertifications product202309EditGlobalProductRequestBodyCertifications = (EditGlobalProductRequestBodyCertifications) o;
        return Objects.equals(this.files, product202309EditGlobalProductRequestBodyCertifications.files) &&
            Objects.equals(this.id, product202309EditGlobalProductRequestBodyCertifications.id) &&
            Objects.equals(this.images, product202309EditGlobalProductRequestBodyCertifications.images);
    }

    @Override
    public int hashCode() {
        return Objects.hash(files, id, images);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class EditGlobalProductRequestBodyCertifications {\n");
        sb.append("    files: ").append(toIndentedString(files)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    images: ").append(toIndentedString(images)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert an instance of EditGlobalProductRequestBodyCertifications to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!EditGlobalProductRequestBodyCertifications.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'EditGlobalProductRequestBodyCertifications' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<EditGlobalProductRequestBodyCertifications> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(EditGlobalProductRequestBodyCertifications.class));

            return (TypeAdapter<T>) new TypeAdapter<EditGlobalProductRequestBodyCertifications>() {
                @Override
                public void write(JsonWriter out, EditGlobalProductRequestBodyCertifications value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public EditGlobalProductRequestBodyCertifications read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }
}

