/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.somle.tiktok.sdk.model.Product.V202309;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.somle.tiktok.sdk.invoke.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * EditGlobalProductRequestBodyProductAttributesValues
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-12T06:25:14.052506Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class EditGlobalProductRequestBodyProductAttributesValues {
    public static final String SERIALIZED_NAME_ID = "id";
    public static final String SERIALIZED_NAME_NAME = "name";
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("id");
        openapiFields.add("name");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    @SerializedName(SERIALIZED_NAME_ID)
    private String id;
    @SerializedName(SERIALIZED_NAME_NAME)
    private String name;

    public EditGlobalProductRequestBodyProductAttributesValues() {
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to EditGlobalProductRequestBodyProductAttributesValues
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!EditGlobalProductRequestBodyProductAttributesValues.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format("The required field(s) %s in EditGlobalProductRequestBodyProductAttributesValues is not found in the empty JSON string", EditGlobalProductRequestBodyProductAttributesValues.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!EditGlobalProductRequestBodyProductAttributesValues.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EditGlobalProductRequestBodyProductAttributesValues` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
        }
        if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
        }
    }

    /**
     * Create an instance of EditGlobalProductRequestBodyProductAttributesValues given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of EditGlobalProductRequestBodyProductAttributesValues
     * @throws IOException if the JSON string is invalid with respect to EditGlobalProductRequestBodyProductAttributesValues
     */
    public static EditGlobalProductRequestBodyProductAttributesValues fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, EditGlobalProductRequestBodyProductAttributesValues.class);
    }

    public EditGlobalProductRequestBodyProductAttributesValues id(String id) {
        this.id = id;
        return this;
    }

    /**
     * The ID of the product attribute value. This is either a built-in product attribute value ID from the [Get Global Attributes API](https://partner.tiktokshop.com/docv2/page/650a0483c16ffe02b8dfc80a) or a custom product attribute value ID returned after calling [Create Global Product API(https://partner.tiktokshop.com/docv2/page/6509de61bace3e02b7489cba).
     *
     * @return id
     **/
    @javax.annotation.Nullable
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public EditGlobalProductRequestBodyProductAttributesValues name(String name) {
        this.name = name;
        return this;
    }

    /**
     * A self-defined custom product attribute value if the built-in values do not satisfy your needs. The system will auto-generate an ID after listing.  **Note**:  - No duplicates allowed under the same attribute. - Max length: 2000 characters - Supports only alphabets and numbers.
     *
     * @return name
     **/
    @javax.annotation.Nullable
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EditGlobalProductRequestBodyProductAttributesValues product202309EditGlobalProductRequestBodyProductAttributesValues = (EditGlobalProductRequestBodyProductAttributesValues) o;
        return Objects.equals(this.id, product202309EditGlobalProductRequestBodyProductAttributesValues.id) &&
            Objects.equals(this.name, product202309EditGlobalProductRequestBodyProductAttributesValues.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class EditGlobalProductRequestBodyProductAttributesValues {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert an instance of EditGlobalProductRequestBodyProductAttributesValues to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!EditGlobalProductRequestBodyProductAttributesValues.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'EditGlobalProductRequestBodyProductAttributesValues' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<EditGlobalProductRequestBodyProductAttributesValues> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(EditGlobalProductRequestBodyProductAttributesValues.class));

            return (TypeAdapter<T>) new TypeAdapter<EditGlobalProductRequestBodyProductAttributesValues>() {
                @Override
                public void write(JsonWriter out, EditGlobalProductRequestBodyProductAttributesValues value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public EditGlobalProductRequestBodyProductAttributesValues read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }
}

