/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.somle.tiktok.sdk.model.Product.V202309;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.somle.tiktok.sdk.invoke.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * GetGlobalProductResponseDataPackageWeight
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-12T06:25:14.052506Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class GetGlobalProductResponseDataPackageWeight {
    public static final String SERIALIZED_NAME_UNIT = "unit";
    public static final String SERIALIZED_NAME_VALUE = "value";
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("unit");
        openapiFields.add("value");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    @SerializedName(SERIALIZED_NAME_UNIT)
    private String unit;
    @SerializedName(SERIALIZED_NAME_VALUE)
    private String value;

    public GetGlobalProductResponseDataPackageWeight() {
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to GetGlobalProductResponseDataPackageWeight
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GetGlobalProductResponseDataPackageWeight.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format("The required field(s) %s in GetGlobalProductResponseDataPackageWeight is not found in the empty JSON string", GetGlobalProductResponseDataPackageWeight.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!GetGlobalProductResponseDataPackageWeight.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetGlobalProductResponseDataPackageWeight` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("unit") != null && !jsonObj.get("unit").isJsonNull()) && !jsonObj.get("unit").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `unit` to be a primitive type in the JSON string but got `%s`", jsonObj.get("unit").toString()));
        }
        if ((jsonObj.get("value") != null && !jsonObj.get("value").isJsonNull()) && !jsonObj.get("value").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("value").toString()));
        }
    }

    /**
     * Create an instance of GetGlobalProductResponseDataPackageWeight given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetGlobalProductResponseDataPackageWeight
     * @throws IOException if the JSON string is invalid with respect to GetGlobalProductResponseDataPackageWeight
     */
    public static GetGlobalProductResponseDataPackageWeight fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, GetGlobalProductResponseDataPackageWeight.class);
    }

    public GetGlobalProductResponseDataPackageWeight unit(String unit) {
        this.unit = unit;
        return this;
    }

    /**
     * The unit for the package weight.
     *
     * @return unit
     **/
    @javax.annotation.Nullable
    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public GetGlobalProductResponseDataPackageWeight value(String value) {
        this.value = value;
        return this;
    }

    /**
     * The package weight.
     *
     * @return value
     **/
    @javax.annotation.Nullable
    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetGlobalProductResponseDataPackageWeight product202309GetGlobalProductResponseDataPackageWeight = (GetGlobalProductResponseDataPackageWeight) o;
        return Objects.equals(this.unit, product202309GetGlobalProductResponseDataPackageWeight.unit) &&
            Objects.equals(this.value, product202309GetGlobalProductResponseDataPackageWeight.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(unit, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetGlobalProductResponseDataPackageWeight {\n");
        sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
        sb.append("    value: ").append(toIndentedString(value)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert an instance of GetGlobalProductResponseDataPackageWeight to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetGlobalProductResponseDataPackageWeight.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'GetGlobalProductResponseDataPackageWeight' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetGlobalProductResponseDataPackageWeight> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(GetGlobalProductResponseDataPackageWeight.class));

            return (TypeAdapter<T>) new TypeAdapter<GetGlobalProductResponseDataPackageWeight>() {
                @Override
                public void write(JsonWriter out, GetGlobalProductResponseDataPackageWeight value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public GetGlobalProductResponseDataPackageWeight read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }
}

