/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.somle.tiktok.sdk.model.Product.V202309;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.somle.tiktok.sdk.invoke.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * GetGlobalProductResponseDataSkusIdentifierCode
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-12T06:25:14.052506Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class GetGlobalProductResponseDataSkusIdentifierCode {
    public static final String SERIALIZED_NAME_CODE = "code";
    public static final String SERIALIZED_NAME_TYPE = "type";
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("code");
        openapiFields.add("type");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    @SerializedName(SERIALIZED_NAME_CODE)
    private String code;
    @SerializedName(SERIALIZED_NAME_TYPE)
    private String type;

    public GetGlobalProductResponseDataSkusIdentifierCode() {
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to GetGlobalProductResponseDataSkusIdentifierCode
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GetGlobalProductResponseDataSkusIdentifierCode.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format("The required field(s) %s in GetGlobalProductResponseDataSkusIdentifierCode is not found in the empty JSON string", GetGlobalProductResponseDataSkusIdentifierCode.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!GetGlobalProductResponseDataSkusIdentifierCode.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetGlobalProductResponseDataSkusIdentifierCode` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("code") != null && !jsonObj.get("code").isJsonNull()) && !jsonObj.get("code").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("code").toString()));
        }
        if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
        }
    }

    /**
     * Create an instance of GetGlobalProductResponseDataSkusIdentifierCode given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetGlobalProductResponseDataSkusIdentifierCode
     * @throws IOException if the JSON string is invalid with respect to GetGlobalProductResponseDataSkusIdentifierCode
     */
    public static GetGlobalProductResponseDataSkusIdentifierCode fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, GetGlobalProductResponseDataSkusIdentifierCode.class);
    }

    public GetGlobalProductResponseDataSkusIdentifierCode code(String code) {
        this.code = code;
        return this;
    }

    /**
     * The identifier code.
     *
     * @return code
     **/
    @javax.annotation.Nullable
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public GetGlobalProductResponseDataSkusIdentifierCode type(String type) {
        this.type = type;
        return this;
    }

    /**
     * The type of identifier code. Possible values: - GTIN - EAN - UPC - ISBN
     *
     * @return type
     **/
    @javax.annotation.Nullable
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetGlobalProductResponseDataSkusIdentifierCode product202309GetGlobalProductResponseDataSkusIdentifierCode = (GetGlobalProductResponseDataSkusIdentifierCode) o;
        return Objects.equals(this.code, product202309GetGlobalProductResponseDataSkusIdentifierCode.code) &&
            Objects.equals(this.type, product202309GetGlobalProductResponseDataSkusIdentifierCode.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(code, type);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetGlobalProductResponseDataSkusIdentifierCode {\n");
        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert an instance of GetGlobalProductResponseDataSkusIdentifierCode to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetGlobalProductResponseDataSkusIdentifierCode.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'GetGlobalProductResponseDataSkusIdentifierCode' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetGlobalProductResponseDataSkusIdentifierCode> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(GetGlobalProductResponseDataSkusIdentifierCode.class));

            return (TypeAdapter<T>) new TypeAdapter<GetGlobalProductResponseDataSkusIdentifierCode>() {
                @Override
                public void write(JsonWriter out, GetGlobalProductResponseDataSkusIdentifierCode value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public GetGlobalProductResponseDataSkusIdentifierCode read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }
}

