/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.somle.tiktok.sdk.model.Product.V202309;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.somle.tiktok.sdk.invoke.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * GetGlobalAttributesResponseDataAttributesRequirementConditions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-12T06:25:14.052506Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class GetGlobalAttributesResponseDataAttributesRequirementConditions {
    public static final String SERIALIZED_NAME_ATTRIBUTE_ID = "attribute_id";
    public static final String SERIALIZED_NAME_ATTRIBUTE_VALUE_ID = "attribute_value_id";
    public static final String SERIALIZED_NAME_CONDITION_TYPE = "condition_type";
    public static final String SERIALIZED_NAME_REGION = "region";
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("attribute_id");
        openapiFields.add("attribute_value_id");
        openapiFields.add("condition_type");
        openapiFields.add("region");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    @SerializedName(SERIALIZED_NAME_ATTRIBUTE_ID)
    private String attributeId;
    @SerializedName(SERIALIZED_NAME_ATTRIBUTE_VALUE_ID)
    private String attributeValueId;
    @SerializedName(SERIALIZED_NAME_CONDITION_TYPE)
    private String conditionType;
    @SerializedName(SERIALIZED_NAME_REGION)
    private String region;

    public GetGlobalAttributesResponseDataAttributesRequirementConditions() {
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to GetGlobalAttributesResponseDataAttributesRequirementConditions
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GetGlobalAttributesResponseDataAttributesRequirementConditions.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format("The required field(s) %s in GetGlobalAttributesResponseDataAttributesRequirementConditions is not found in the empty JSON string", GetGlobalAttributesResponseDataAttributesRequirementConditions.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!GetGlobalAttributesResponseDataAttributesRequirementConditions.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetGlobalAttributesResponseDataAttributesRequirementConditions` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("attribute_id") != null && !jsonObj.get("attribute_id").isJsonNull()) && !jsonObj.get("attribute_id").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `attribute_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("attribute_id").toString()));
        }
        if ((jsonObj.get("attribute_value_id") != null && !jsonObj.get("attribute_value_id").isJsonNull()) && !jsonObj.get("attribute_value_id").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `attribute_value_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("attribute_value_id").toString()));
        }
        if ((jsonObj.get("condition_type") != null && !jsonObj.get("condition_type").isJsonNull()) && !jsonObj.get("condition_type").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `condition_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("condition_type").toString()));
        }
        if ((jsonObj.get("region") != null && !jsonObj.get("region").isJsonNull()) && !jsonObj.get("region").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `region` to be a primitive type in the JSON string but got `%s`", jsonObj.get("region").toString()));
        }
    }

    /**
     * Create an instance of GetGlobalAttributesResponseDataAttributesRequirementConditions given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetGlobalAttributesResponseDataAttributesRequirementConditions
     * @throws IOException if the JSON string is invalid with respect to GetGlobalAttributesResponseDataAttributesRequirementConditions
     */
    public static GetGlobalAttributesResponseDataAttributesRequirementConditions fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, GetGlobalAttributesResponseDataAttributesRequirementConditions.class);
    }

    public GetGlobalAttributesResponseDataAttributesRequirementConditions attributeId(String attributeId) {
        this.attributeId = attributeId;
        return this;
    }

    /**
     * The ID of the product attribute that is being evaluated by the condition.
     *
     * @return attributeId
     **/
    @javax.annotation.Nullable
    public String getAttributeId() {
        return attributeId;
    }

    public void setAttributeId(String attributeId) {
        this.attributeId = attributeId;
    }

    public GetGlobalAttributesResponseDataAttributesRequirementConditions attributeValueId(String attributeValueId) {
        this.attributeValueId = attributeValueId;
        return this;
    }

    /**
     * The ID of the product attribute value that must match the seller&#39;s input for the condition to be true.
     *
     * @return attributeValueId
     **/
    @javax.annotation.Nullable
    public String getAttributeValueId() {
        return attributeValueId;
    }

    public void setAttributeValueId(String attributeValueId) {
        this.attributeValueId = attributeValueId;
    }

    public GetGlobalAttributesResponseDataAttributesRequirementConditions conditionType(String conditionType) {
        this.conditionType = conditionType;
        return this;
    }

    /**
     * The type of condition, such as matching values, or range comparisons. Possible values: - VALUE_ID_MATCH: The condition is true when the seller selects a value whose ID matches the one specified in this condition.
     *
     * @return conditionType
     **/
    @javax.annotation.Nullable
    public String getConditionType() {
        return conditionType;
    }

    public void setConditionType(String conditionType) {
        this.conditionType = conditionType;
    }

    public GetGlobalAttributesResponseDataAttributesRequirementConditions region(String region) {
        this.region = region;
        return this;
    }

    /**
     * The market where the attribute is required when the conditions are met. Possible values: - DE: Germany - ES: Spain - FR: France - GB: United Kingdom - ID: Indonesia - IT: Italy - IE: Ireland - JP: Japan - MY: Malaysia - PH: Philippines - SG: Singapore - TH: Thailand - US: United States - VN: Vietnam
     *
     * @return region
     **/
    @javax.annotation.Nullable
    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetGlobalAttributesResponseDataAttributesRequirementConditions product202309GetGlobalAttributesResponseDataAttributesRequirementConditions = (GetGlobalAttributesResponseDataAttributesRequirementConditions) o;
        return Objects.equals(this.attributeId, product202309GetGlobalAttributesResponseDataAttributesRequirementConditions.attributeId) &&
            Objects.equals(this.attributeValueId, product202309GetGlobalAttributesResponseDataAttributesRequirementConditions.attributeValueId) &&
            Objects.equals(this.conditionType, product202309GetGlobalAttributesResponseDataAttributesRequirementConditions.conditionType) &&
            Objects.equals(this.region, product202309GetGlobalAttributesResponseDataAttributesRequirementConditions.region);
    }

    @Override
    public int hashCode() {
        return Objects.hash(attributeId, attributeValueId, conditionType, region);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetGlobalAttributesResponseDataAttributesRequirementConditions {\n");
        sb.append("    attributeId: ").append(toIndentedString(attributeId)).append("\n");
        sb.append("    attributeValueId: ").append(toIndentedString(attributeValueId)).append("\n");
        sb.append("    conditionType: ").append(toIndentedString(conditionType)).append("\n");
        sb.append("    region: ").append(toIndentedString(region)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert an instance of GetGlobalAttributesResponseDataAttributesRequirementConditions to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetGlobalAttributesResponseDataAttributesRequirementConditions.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'GetGlobalAttributesResponseDataAttributesRequirementConditions' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetGlobalAttributesResponseDataAttributesRequirementConditions> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(GetGlobalAttributesResponseDataAttributesRequirementConditions.class));

            return (TypeAdapter<T>) new TypeAdapter<GetGlobalAttributesResponseDataAttributesRequirementConditions>() {
                @Override
                public void write(JsonWriter out, GetGlobalAttributesResponseDataAttributesRequirementConditions value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public GetGlobalAttributesResponseDataAttributesRequirementConditions read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }
}

