/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.somle.tiktok.sdk.model.Product.V202309;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.somle.tiktok.sdk.invoke.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * GetProductResponseDataIntegratedPlatformStatuses
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-12T06:25:14.052506Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class GetProductResponseDataIntegratedPlatformStatuses {
    public static final String SERIALIZED_NAME_PLATFORM = "platform";
    public static final String SERIALIZED_NAME_STATUS = "status";
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("platform");
        openapiFields.add("status");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    @SerializedName(SERIALIZED_NAME_PLATFORM)
    private String platform;
    @SerializedName(SERIALIZED_NAME_STATUS)
    private String status;

    public GetProductResponseDataIntegratedPlatformStatuses() {
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to GetProductResponseDataIntegratedPlatformStatuses
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GetProductResponseDataIntegratedPlatformStatuses.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format("The required field(s) %s in GetProductResponseDataIntegratedPlatformStatuses is not found in the empty JSON string", GetProductResponseDataIntegratedPlatformStatuses.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!GetProductResponseDataIntegratedPlatformStatuses.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetProductResponseDataIntegratedPlatformStatuses` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("platform") != null && !jsonObj.get("platform").isJsonNull()) && !jsonObj.get("platform").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `platform` to be a primitive type in the JSON string but got `%s`", jsonObj.get("platform").toString()));
        }
        if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
        }
    }

    /**
     * Create an instance of GetProductResponseDataIntegratedPlatformStatuses given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetProductResponseDataIntegratedPlatformStatuses
     * @throws IOException if the JSON string is invalid with respect to GetProductResponseDataIntegratedPlatformStatuses
     */
    public static GetProductResponseDataIntegratedPlatformStatuses fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, GetProductResponseDataIntegratedPlatformStatuses.class);
    }

    public GetProductResponseDataIntegratedPlatformStatuses platform(String platform) {
        this.platform = platform;
        return this;
    }

    /**
     * The integrated platform name. Possible values: - TOKOPEDIA
     *
     * @return platform
     **/
    @javax.annotation.Nullable
    public String getPlatform() {
        return platform;
    }

    public void setPlatform(String platform) {
        this.platform = platform;
    }

    public GetProductResponseDataIntegratedPlatformStatuses status(String status) {
        this.status = status;
        return this;
    }

    /**
     * The product status in the integrated platform. Possible values: - DRAFT - PENDING - FAILED - ACTIVATE - SELLER_DEACTIVATED - PLATFORM_DEACTIVATED - FREEZE - DELETED
     *
     * @return status
     **/
    @javax.annotation.Nullable
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetProductResponseDataIntegratedPlatformStatuses product202309GetProductResponseDataIntegratedPlatformStatuses = (GetProductResponseDataIntegratedPlatformStatuses) o;
        return Objects.equals(this.platform, product202309GetProductResponseDataIntegratedPlatformStatuses.platform) &&
            Objects.equals(this.status, product202309GetProductResponseDataIntegratedPlatformStatuses.status);
    }

    @Override
    public int hashCode() {
        return Objects.hash(platform, status);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetProductResponseDataIntegratedPlatformStatuses {\n");
        sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert an instance of GetProductResponseDataIntegratedPlatformStatuses to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetProductResponseDataIntegratedPlatformStatuses.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'GetProductResponseDataIntegratedPlatformStatuses' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetProductResponseDataIntegratedPlatformStatuses> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(GetProductResponseDataIntegratedPlatformStatuses.class));

            return (TypeAdapter<T>) new TypeAdapter<GetProductResponseDataIntegratedPlatformStatuses>() {
                @Override
                public void write(JsonWriter out, GetProductResponseDataIntegratedPlatformStatuses value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public GetProductResponseDataIntegratedPlatformStatuses read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }
}

