/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.somle.tiktok.sdk.model.Product.V202309;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.somle.tiktok.sdk.invoke.JSON;

import java.io.IOException;
import java.util.*;

/**
 * GetProductResponseDataAudit
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-12T06:25:14.052506Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class GetProductResponseDataAudit {
    public static final String SERIALIZED_NAME_PRE_APPROVED_REASONS = "pre_approved_reasons";
    public static final String SERIALIZED_NAME_STATUS = "status";
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("pre_approved_reasons");
        openapiFields.add("status");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    @SerializedName(SERIALIZED_NAME_PRE_APPROVED_REASONS)
    private List<String> preApprovedReasons = new ArrayList<>();
    @SerializedName(SERIALIZED_NAME_STATUS)
    private String status;

    public GetProductResponseDataAudit() {
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to GetProductResponseDataAudit
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GetProductResponseDataAudit.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format("The required field(s) %s in GetProductResponseDataAudit is not found in the empty JSON string", GetProductResponseDataAudit.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!GetProductResponseDataAudit.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetProductResponseDataAudit` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // ensure the optional json data is an array if present
        if (jsonObj.get("pre_approved_reasons") != null && !jsonObj.get("pre_approved_reasons").isJsonNull() && !jsonObj.get("pre_approved_reasons").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `pre_approved_reasons` to be an array in the JSON string but got `%s`", jsonObj.get("pre_approved_reasons").toString()));
        }
        if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
        }
    }

    /**
     * Create an instance of GetProductResponseDataAudit given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetProductResponseDataAudit
     * @throws IOException if the JSON string is invalid with respect to GetProductResponseDataAudit
     */
    public static GetProductResponseDataAudit fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, GetProductResponseDataAudit.class);
    }

    public GetProductResponseDataAudit preApprovedReasons(List<String> preApprovedReasons) {
        this.preApprovedReasons = preApprovedReasons;
        return this;
    }

    public GetProductResponseDataAudit addPreApprovedReasonsItem(String preApprovedReasonsItem) {
        if (this.preApprovedReasons == null) {
            this.preApprovedReasons = new ArrayList<>();
        }
        this.preApprovedReasons.add(preApprovedReasonsItem);
        return this;
    }

    /**
     * The reason why the product is pre-approved.  Applicable only if &#x60;audit.status&#x3D;PRE_APPROVED&#x60;, otherwise returns an empty array.  Possible values: - KYC_PENDING: The seller&#39;s onboarding (KYC - Know Your Customer information) is incomplete or awaiting processing. - RESTRICTED_CATEGORY_PENDING: The product is in a restricted category, and category approval is still pending. To request access, submit an application through the Qualification Center on TikTok Shop Seller Center. Applicable only for the US market.
     *
     * @return preApprovedReasons
     **/
    @javax.annotation.Nullable
    public List<String> getPreApprovedReasons() {
        return preApprovedReasons;
    }

    public void setPreApprovedReasons(List<String> preApprovedReasons) {
        this.preApprovedReasons = preApprovedReasons;
    }

    public GetProductResponseDataAudit status(String status) {
        this.status = status;
        return this;
    }

    /**
     * The product audit status. Possible values:  - NONE: The product is not applicable for audit because it has not been submitted for listing on this platform, or it is in a draft, frozen, or deactivated state. - AUDITING: The product is currently being audited. - FAILED: The product failed the audit, or the audit was cancelled. - PRE_APPROVED: The product has passed the audit but is not yet listed due to pending prerequisites. Refer to &#x60;pre_approved_reasons&#x60; for the prerequisites. - APPROVED: The product passed the audit and has been listed on the platform.
     *
     * @return status
     **/
    @javax.annotation.Nullable
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetProductResponseDataAudit product202309GetProductResponseDataAudit = (GetProductResponseDataAudit) o;
        return Objects.equals(this.preApprovedReasons, product202309GetProductResponseDataAudit.preApprovedReasons) &&
            Objects.equals(this.status, product202309GetProductResponseDataAudit.status);
    }

    @Override
    public int hashCode() {
        return Objects.hash(preApprovedReasons, status);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetProductResponseDataAudit {\n");
        sb.append("    preApprovedReasons: ").append(toIndentedString(preApprovedReasons)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert an instance of GetProductResponseDataAudit to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetProductResponseDataAudit.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'GetProductResponseDataAudit' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetProductResponseDataAudit> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(GetProductResponseDataAudit.class));

            return (TypeAdapter<T>) new TypeAdapter<GetProductResponseDataAudit>() {
                @Override
                public void write(JsonWriter out, GetProductResponseDataAudit value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public GetProductResponseDataAudit read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }
}

