/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.somle.tiktok.sdk.model.Product.V202309;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.somle.tiktok.sdk.invoke.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * PartialEditProductRequestBodyCertificationsImages
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-12T06:25:14.052506Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class PartialEditProductRequestBodyCertificationsImages {
    public static final String SERIALIZED_NAME_URI = "uri";
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("uri");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    @SerializedName(SERIALIZED_NAME_URI)
    private String uri;

    public PartialEditProductRequestBodyCertificationsImages() {
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to PartialEditProductRequestBodyCertificationsImages
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!PartialEditProductRequestBodyCertificationsImages.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format("The required field(s) %s in PartialEditProductRequestBodyCertificationsImages is not found in the empty JSON string", PartialEditProductRequestBodyCertificationsImages.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!PartialEditProductRequestBodyCertificationsImages.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PartialEditProductRequestBodyCertificationsImages` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("uri") != null && !jsonObj.get("uri").isJsonNull()) && !jsonObj.get("uri").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `uri` to be a primitive type in the JSON string but got `%s`", jsonObj.get("uri").toString()));
        }
    }

    /**
     * Create an instance of PartialEditProductRequestBodyCertificationsImages given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of PartialEditProductRequestBodyCertificationsImages
     * @throws IOException if the JSON string is invalid with respect to PartialEditProductRequestBodyCertificationsImages
     */
    public static PartialEditProductRequestBodyCertificationsImages fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, PartialEditProductRequestBodyCertificationsImages.class);
    }

    public PartialEditProductRequestBodyCertificationsImages uri(String uri) {
        this.uri = uri;
        return this;
    }

    /**
     * The URI of the image.  Obtain this URI by uploading the images through the [Upload Product Image API](6509df95defece02be598a22)  with &#x60;use_case&#x3D;CERTIFICATION_IMAGE&#x60;.
     *
     * @return uri
     **/
    @javax.annotation.Nullable
    public String getUri() {
        return uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PartialEditProductRequestBodyCertificationsImages product202309PartialEditProductRequestBodyCertificationsImages = (PartialEditProductRequestBodyCertificationsImages) o;
        return Objects.equals(this.uri, product202309PartialEditProductRequestBodyCertificationsImages.uri);
    }

    @Override
    public int hashCode() {
        return Objects.hash(uri);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PartialEditProductRequestBodyCertificationsImages {\n");
        sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert an instance of PartialEditProductRequestBodyCertificationsImages to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!PartialEditProductRequestBodyCertificationsImages.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'PartialEditProductRequestBodyCertificationsImages' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<PartialEditProductRequestBodyCertificationsImages> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(PartialEditProductRequestBodyCertificationsImages.class));

            return (TypeAdapter<T>) new TypeAdapter<PartialEditProductRequestBodyCertificationsImages>() {
                @Override
                public void write(JsonWriter out, PartialEditProductRequestBodyCertificationsImages value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public PartialEditProductRequestBodyCertificationsImages read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }
}

