/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.somle.tiktok.sdk.model.Product.V202309;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.somle.tiktok.sdk.invoke.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * PartialEditProductRequestBodySkusPreSale
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-12T06:25:14.052506Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class PartialEditProductRequestBodySkusPreSale {
    public static final String SERIALIZED_NAME_FULFILLMENT_TYPE = "fulfillment_type";
    public static final String SERIALIZED_NAME_TYPE = "type";
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("fulfillment_type");
        openapiFields.add("type");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    @SerializedName(SERIALIZED_NAME_FULFILLMENT_TYPE)
    private PartialEditProductRequestBodySkusPreSaleFulfillmentType fulfillmentType;
    @SerializedName(SERIALIZED_NAME_TYPE)
    private String type;

    public PartialEditProductRequestBodySkusPreSale() {
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to PartialEditProductRequestBodySkusPreSale
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!PartialEditProductRequestBodySkusPreSale.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format("The required field(s) %s in PartialEditProductRequestBodySkusPreSale is not found in the empty JSON string", PartialEditProductRequestBodySkusPreSale.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!PartialEditProductRequestBodySkusPreSale.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PartialEditProductRequestBodySkusPreSale` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // validate the optional field `fulfillment_type`
        if (jsonObj.get("fulfillment_type") != null && !jsonObj.get("fulfillment_type").isJsonNull()) {
            PartialEditProductRequestBodySkusPreSaleFulfillmentType.validateJsonElement(jsonObj.get("fulfillment_type"));
        }
        if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
        }
    }

    /**
     * Create an instance of PartialEditProductRequestBodySkusPreSale given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of PartialEditProductRequestBodySkusPreSale
     * @throws IOException if the JSON string is invalid with respect to PartialEditProductRequestBodySkusPreSale
     */
    public static PartialEditProductRequestBodySkusPreSale fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, PartialEditProductRequestBodySkusPreSale.class);
    }

    public PartialEditProductRequestBodySkusPreSale fulfillmentType(PartialEditProductRequestBodySkusPreSaleFulfillmentType fulfillmentType) {
        this.fulfillmentType = fulfillmentType;
        return this;
    }

    /**
     * Get fulfillmentType
     *
     * @return fulfillmentType
     **/
    @javax.annotation.Nullable
    public PartialEditProductRequestBodySkusPreSaleFulfillmentType getFulfillmentType() {
        return fulfillmentType;
    }

    public void setFulfillmentType(PartialEditProductRequestBodySkusPreSaleFulfillmentType fulfillmentType) {
        this.fulfillmentType = fulfillmentType;
    }

    public PartialEditProductRequestBodySkusPreSale type(String type) {
        this.type = type;
        return this;
    }

    /**
     * The type of pre-sale. Possible values based on the region: **US** - &#x60;PRE_ORDER&#x60;: The product is not yet available or released. Fulfillment can be extended by specifying a release date. - &#x60;MADE_TO_ORDER&#x60;: The product is produced only after the order is received. Fulfillment can be extended by specifying a duration. - &#x60;CUSTOM&#x60;: The product requires a fulfillment timeline that exceeds the standard due to other factors. Fulfillment can be extended by specifying a duration.  **UK and SEA** - &#x60;PRE_ORDER&#x60;: The product is not yet available or released. Fulfillment can be extended by specifying a duration.   **ALL** - &#x60;NONE&#x60;: To convert the product to a regular (non-presale) product.
     *
     * @return type
     **/
    @javax.annotation.Nullable
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PartialEditProductRequestBodySkusPreSale product202309PartialEditProductRequestBodySkusPreSale = (PartialEditProductRequestBodySkusPreSale) o;
        return Objects.equals(this.fulfillmentType, product202309PartialEditProductRequestBodySkusPreSale.fulfillmentType) &&
            Objects.equals(this.type, product202309PartialEditProductRequestBodySkusPreSale.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(fulfillmentType, type);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PartialEditProductRequestBodySkusPreSale {\n");
        sb.append("    fulfillmentType: ").append(toIndentedString(fulfillmentType)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert an instance of PartialEditProductRequestBodySkusPreSale to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!PartialEditProductRequestBodySkusPreSale.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'PartialEditProductRequestBodySkusPreSale' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<PartialEditProductRequestBodySkusPreSale> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(PartialEditProductRequestBodySkusPreSale.class));

            return (TypeAdapter<T>) new TypeAdapter<PartialEditProductRequestBodySkusPreSale>() {
                @Override
                public void write(JsonWriter out, PartialEditProductRequestBodySkusPreSale value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public PartialEditProductRequestBodySkusPreSale read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }
}

