/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.somle.tiktok.sdk.model.Product.V202309;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.somle.tiktok.sdk.invoke.JSON;

import java.io.IOException;
import java.util.*;

/**
 * UpdateGlobalInventoryRequestBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-12T06:25:14.052506Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class UpdateGlobalInventoryRequestBody {
    public static final String SERIALIZED_NAME_GLOBAL_SKUS = "global_skus";
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("global_skus");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    @SerializedName(SERIALIZED_NAME_GLOBAL_SKUS)
    private List<UpdateGlobalInventoryRequestBodyGlobalSkus> globalSkus = new ArrayList<>();

    public UpdateGlobalInventoryRequestBody() {
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to UpdateGlobalInventoryRequestBody
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!UpdateGlobalInventoryRequestBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateGlobalInventoryRequestBody is not found in the empty JSON string", UpdateGlobalInventoryRequestBody.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!UpdateGlobalInventoryRequestBody.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UpdateGlobalInventoryRequestBody` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (jsonObj.get("global_skus") != null && !jsonObj.get("global_skus").isJsonNull()) {
            JsonArray jsonArrayglobalSkus = jsonObj.getAsJsonArray("global_skus");
            if (jsonArrayglobalSkus != null) {
                // ensure the json data is an array
                if (!jsonObj.get("global_skus").isJsonArray()) {
                    throw new IllegalArgumentException(String.format("Expected the field `global_skus` to be an array in the JSON string but got `%s`", jsonObj.get("global_skus").toString()));
                }

                // validate the optional field `global_skus` (array)
                for (int i = 0; i < jsonArrayglobalSkus.size(); i++) {
                    UpdateGlobalInventoryRequestBodyGlobalSkus.validateJsonElement(jsonArrayglobalSkus.get(i));
                }
                ;
            }
        }
    }

    /**
     * Create an instance of UpdateGlobalInventoryRequestBody given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of UpdateGlobalInventoryRequestBody
     * @throws IOException if the JSON string is invalid with respect to UpdateGlobalInventoryRequestBody
     */
    public static UpdateGlobalInventoryRequestBody fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, UpdateGlobalInventoryRequestBody.class);
    }

    public UpdateGlobalInventoryRequestBody globalSkus(List<UpdateGlobalInventoryRequestBodyGlobalSkus> globalSkus) {
        this.globalSkus = globalSkus;
        return this;
    }

    public UpdateGlobalInventoryRequestBody addGlobalSkusItem(UpdateGlobalInventoryRequestBodyGlobalSkus globalSkusItem) {
        if (this.globalSkus == null) {
            this.globalSkus = new ArrayList<>();
        }
        this.globalSkus.add(globalSkusItem);
        return this;
    }

    /**
     * The list of global SKUs that need to be updated.
     *
     * @return globalSkus
     **/
    @javax.annotation.Nullable
    public List<UpdateGlobalInventoryRequestBodyGlobalSkus> getGlobalSkus() {
        return globalSkus;
    }

    public void setGlobalSkus(List<UpdateGlobalInventoryRequestBodyGlobalSkus> globalSkus) {
        this.globalSkus = globalSkus;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateGlobalInventoryRequestBody product202309UpdateGlobalInventoryRequestBody = (UpdateGlobalInventoryRequestBody) o;
        return Objects.equals(this.globalSkus, product202309UpdateGlobalInventoryRequestBody.globalSkus);
    }

    @Override
    public int hashCode() {
        return Objects.hash(globalSkus);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UpdateGlobalInventoryRequestBody {\n");
        sb.append("    globalSkus: ").append(toIndentedString(globalSkus)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert an instance of UpdateGlobalInventoryRequestBody to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!UpdateGlobalInventoryRequestBody.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'UpdateGlobalInventoryRequestBody' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<UpdateGlobalInventoryRequestBody> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(UpdateGlobalInventoryRequestBody.class));

            return (TypeAdapter<T>) new TypeAdapter<UpdateGlobalInventoryRequestBody>() {
                @Override
                public void write(JsonWriter out, UpdateGlobalInventoryRequestBody value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public UpdateGlobalInventoryRequestBody read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }
}

