/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.somle.tiktok.sdk.model.Product.V202309;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.somle.tiktok.sdk.invoke.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * UpdatePriceRequestBodySkusListPrice
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-12T06:25:14.052506Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class UpdatePriceRequestBodySkusListPrice {
    public static final String SERIALIZED_NAME_AMOUNT = "amount";
    public static final String SERIALIZED_NAME_CURRENCY = "currency";
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("amount");
        openapiFields.add("currency");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    @SerializedName(SERIALIZED_NAME_AMOUNT)
    private String amount;
    @SerializedName(SERIALIZED_NAME_CURRENCY)
    private String currency;

    public UpdatePriceRequestBodySkusListPrice() {
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to UpdatePriceRequestBodySkusListPrice
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!UpdatePriceRequestBodySkusListPrice.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format("The required field(s) %s in UpdatePriceRequestBodySkusListPrice is not found in the empty JSON string", UpdatePriceRequestBodySkusListPrice.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!UpdatePriceRequestBodySkusListPrice.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UpdatePriceRequestBodySkusListPrice` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("amount") != null && !jsonObj.get("amount").isJsonNull()) && !jsonObj.get("amount").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("amount").toString()));
        }
        if ((jsonObj.get("currency") != null && !jsonObj.get("currency").isJsonNull()) && !jsonObj.get("currency").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
        }
    }

    /**
     * Create an instance of UpdatePriceRequestBodySkusListPrice given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of UpdatePriceRequestBodySkusListPrice
     * @throws IOException if the JSON string is invalid with respect to UpdatePriceRequestBodySkusListPrice
     */
    public static UpdatePriceRequestBodySkusListPrice fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, UpdatePriceRequestBodySkusListPrice.class);
    }

    public UpdatePriceRequestBodySkusListPrice amount(String amount) {
        this.amount = amount;
        return this;
    }

    /**
     * The price amount. Valid range: [0.01, 7600]   **Note**:  - The value must be equal to or greater than &#x60;skus.price.amount&#x60;. Otherwise, it will be discarded. - If the value is verified to be legitimate by the audit team, it will be stored and returned in the [Get Product API](6509d85b4a0bb702c057fdda).
     *
     * @return amount
     **/
    @javax.annotation.Nullable
    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public UpdatePriceRequestBodySkusListPrice currency(String currency) {
        this.currency = currency;
        return this;
    }

    /**
     * The currency. Possible values: USD
     *
     * @return currency
     **/
    @javax.annotation.Nullable
    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdatePriceRequestBodySkusListPrice product202309UpdatePriceRequestBodySkusListPrice = (UpdatePriceRequestBodySkusListPrice) o;
        return Objects.equals(this.amount, product202309UpdatePriceRequestBodySkusListPrice.amount) &&
            Objects.equals(this.currency, product202309UpdatePriceRequestBodySkusListPrice.currency);
    }

    @Override
    public int hashCode() {
        return Objects.hash(amount, currency);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UpdatePriceRequestBodySkusListPrice {\n");
        sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert an instance of UpdatePriceRequestBodySkusListPrice to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!UpdatePriceRequestBodySkusListPrice.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'UpdatePriceRequestBodySkusListPrice' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<UpdatePriceRequestBodySkusListPrice> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(UpdatePriceRequestBodySkusListPrice.class));

            return (TypeAdapter<T>) new TypeAdapter<UpdatePriceRequestBodySkusListPrice>() {
                @Override
                public void write(JsonWriter out, UpdatePriceRequestBodySkusListPrice value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public UpdatePriceRequestBodySkusListPrice read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }
}

