
#spring:
#  # h2:
#  #   console:
#  #     enabled: true
#  # datasource:
#  #   url: jdbc:h2:mem:testdb
#  #   driverClassName: org.h2.Driver
#  #   username: sa
#  #   password: password
#  devtools:
#    restart:
#      enabled: false
#  jpa:
#    properties:
#      hibernate:
#        # show_sql: true
#        format_sql: true
#        # type: trace
#        # use_sql_comments: true
#        # generate_statistics: true
#    hibernate:
#      ddl-auto: update
#      # format_sql: true
#    # show-sql: true


oss:
  endpoint: https://oss-cn-hangzhou.aliyuncs.com

