/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.somle.tiktok.sdk.model.Order.V202309;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.somle.tiktok.sdk.invoke.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;


/**
 * GetOrderListResponseDataOrdersHandlingDuration
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-12T06:25:14.052506Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class GetOrderListResponseDataOrdersHandlingDuration {
    public static final String SERIALIZED_NAME_DAYS = "days";
    public static final String SERIALIZED_NAME_TYPE = "type";
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("days");
        openapiFields.add("type");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    @SerializedName(SERIALIZED_NAME_DAYS)
    private String days;
    @SerializedName(SERIALIZED_NAME_TYPE)
    private String type;

    public GetOrderListResponseDataOrdersHandlingDuration() {
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to GetOrderListResponseDataOrdersHandlingDuration
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GetOrderListResponseDataOrdersHandlingDuration.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format("The required field(s) %s in GetOrderListResponseDataOrdersHandlingDuration is not found in the empty JSON string", GetOrderListResponseDataOrdersHandlingDuration.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!GetOrderListResponseDataOrdersHandlingDuration.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetOrderListResponseDataOrdersHandlingDuration` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("days") != null && !jsonObj.get("days").isJsonNull()) && !jsonObj.get("days").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `days` to be a primitive type in the JSON string but got `%s`", jsonObj.get("days").toString()));
        }
        if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
        }
    }

    /**
     * Create an instance of GetOrderListResponseDataOrdersHandlingDuration given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetOrderListResponseDataOrdersHandlingDuration
     * @throws IOException if the JSON string is invalid with respect to GetOrderListResponseDataOrdersHandlingDuration
     */
    public static GetOrderListResponseDataOrdersHandlingDuration fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, GetOrderListResponseDataOrdersHandlingDuration.class);
    }

    public GetOrderListResponseDataOrdersHandlingDuration days(String days) {
        this.days = days;
        return this;
    }

    /**
     * The number of days.
     *
     * @return days
     **/
    @javax.annotation.Nullable
    public String getDays() {
        return days;
    }

    public void setDays(String days) {
        this.days = days;
    }

    public GetOrderListResponseDataOrdersHandlingDuration type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Indicates if the duration is calculated in calendar days or business days. Possible values: - &#x60;CALENDAR_DAY&#x60;: Represents consecutive days, including weekends and holidays. - &#x60;BUSINESS_DAY&#x60;: Represents business days, excluding weekends and public holidays. Default: &#x60;BUSINESS_DAY&#x60;
     *
     * @return type
     **/
    @javax.annotation.Nullable
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetOrderListResponseDataOrdersHandlingDuration order202309GetOrderListResponseDataOrdersHandlingDuration = (GetOrderListResponseDataOrdersHandlingDuration) o;
        return Objects.equals(this.days, order202309GetOrderListResponseDataOrdersHandlingDuration.days) &&
            Objects.equals(this.type, order202309GetOrderListResponseDataOrdersHandlingDuration.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(days, type);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetOrderListResponseDataOrdersHandlingDuration {\n");
        sb.append("    days: ").append(toIndentedString(days)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert an instance of GetOrderListResponseDataOrdersHandlingDuration to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetOrderListResponseDataOrdersHandlingDuration.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'GetOrderListResponseDataOrdersHandlingDuration' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetOrderListResponseDataOrdersHandlingDuration> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(GetOrderListResponseDataOrdersHandlingDuration.class));

            return (TypeAdapter<T>) new TypeAdapter<GetOrderListResponseDataOrdersHandlingDuration>() {
                @Override
                public void write(JsonWriter out, GetOrderListResponseDataOrdersHandlingDuration value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public GetOrderListResponseDataOrdersHandlingDuration read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }
}

