/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.somle.tiktok.sdk.model.Order.V202309;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.somle.tiktok.sdk.invoke.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * GetOrderDetailResponseDataOrdersLineItemsItemTax
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-12T06:25:14.052506Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class GetOrderDetailResponseDataOrdersLineItemsItemTax {
    public static final String SERIALIZED_NAME_TAX_AMOUNT = "tax_amount";
    public static final String SERIALIZED_NAME_TAX_RATE = "tax_rate";
    public static final String SERIALIZED_NAME_TAX_TYPE = "tax_type";
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("tax_amount");
        openapiFields.add("tax_rate");
        openapiFields.add("tax_type");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    @SerializedName(SERIALIZED_NAME_TAX_AMOUNT)
    private String taxAmount;
    @SerializedName(SERIALIZED_NAME_TAX_RATE)
    private String taxRate;
    @SerializedName(SERIALIZED_NAME_TAX_TYPE)
    private String taxType;

    public GetOrderDetailResponseDataOrdersLineItemsItemTax() {
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to GetOrderDetailResponseDataOrdersLineItemsItemTax
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GetOrderDetailResponseDataOrdersLineItemsItemTax.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format("The required field(s) %s in GetOrderDetailResponseDataOrdersLineItemsItemTax is not found in the empty JSON string", GetOrderDetailResponseDataOrdersLineItemsItemTax.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!GetOrderDetailResponseDataOrdersLineItemsItemTax.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetOrderDetailResponseDataOrdersLineItemsItemTax` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("tax_amount") != null && !jsonObj.get("tax_amount").isJsonNull()) && !jsonObj.get("tax_amount").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `tax_amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tax_amount").toString()));
        }
        if ((jsonObj.get("tax_rate") != null && !jsonObj.get("tax_rate").isJsonNull()) && !jsonObj.get("tax_rate").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `tax_rate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tax_rate").toString()));
        }
        if ((jsonObj.get("tax_type") != null && !jsonObj.get("tax_type").isJsonNull()) && !jsonObj.get("tax_type").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `tax_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tax_type").toString()));
        }
    }

    /**
     * Create an instance of GetOrderDetailResponseDataOrdersLineItemsItemTax given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetOrderDetailResponseDataOrdersLineItemsItemTax
     * @throws IOException if the JSON string is invalid with respect to GetOrderDetailResponseDataOrdersLineItemsItemTax
     */
    public static GetOrderDetailResponseDataOrdersLineItemsItemTax fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, GetOrderDetailResponseDataOrdersLineItemsItemTax.class);
    }

    public GetOrderDetailResponseDataOrdersLineItemsItemTax taxAmount(String taxAmount) {
        this.taxAmount = taxAmount;
        return this;
    }

    /**
     * Tax amount.
     *
     * @return taxAmount
     **/
    @javax.annotation.Nullable
    public String getTaxAmount() {
        return taxAmount;
    }

    public void setTaxAmount(String taxAmount) {
        this.taxAmount = taxAmount;
    }

    public GetOrderDetailResponseDataOrdersLineItemsItemTax taxRate(String taxRate) {
        this.taxRate = taxRate;
        return this;
    }

    /**
     * Tax rate.
     *
     * @return taxRate
     **/
    @javax.annotation.Nullable
    public String getTaxRate() {
        return taxRate;
    }

    public void setTaxRate(String taxRate) {
        this.taxRate = taxRate;
    }

    public GetOrderDetailResponseDataOrdersLineItemsItemTax taxType(String taxType) {
        this.taxType = taxType;
        return this;
    }

    /**
     * Tax type. - &#x60;SALES_TAX&#x60; (US market sales tax) Currently only sales tax is available.
     *
     * @return taxType
     **/
    @javax.annotation.Nullable
    public String getTaxType() {
        return taxType;
    }

    public void setTaxType(String taxType) {
        this.taxType = taxType;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetOrderDetailResponseDataOrdersLineItemsItemTax order202309GetOrderDetailResponseDataOrdersLineItemsItemTax = (GetOrderDetailResponseDataOrdersLineItemsItemTax) o;
        return Objects.equals(this.taxAmount, order202309GetOrderDetailResponseDataOrdersLineItemsItemTax.taxAmount) &&
            Objects.equals(this.taxRate, order202309GetOrderDetailResponseDataOrdersLineItemsItemTax.taxRate) &&
            Objects.equals(this.taxType, order202309GetOrderDetailResponseDataOrdersLineItemsItemTax.taxType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(taxAmount, taxRate, taxType);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetOrderDetailResponseDataOrdersLineItemsItemTax {\n");
        sb.append("    taxAmount: ").append(toIndentedString(taxAmount)).append("\n");
        sb.append("    taxRate: ").append(toIndentedString(taxRate)).append("\n");
        sb.append("    taxType: ").append(toIndentedString(taxType)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert an instance of GetOrderDetailResponseDataOrdersLineItemsItemTax to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetOrderDetailResponseDataOrdersLineItemsItemTax.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'GetOrderDetailResponseDataOrdersLineItemsItemTax' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetOrderDetailResponseDataOrdersLineItemsItemTax> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(GetOrderDetailResponseDataOrdersLineItemsItemTax.class));

            return (TypeAdapter<T>) new TypeAdapter<GetOrderDetailResponseDataOrdersLineItemsItemTax>() {
                @Override
                public void write(JsonWriter out, GetOrderDetailResponseDataOrdersLineItemsItemTax value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public GetOrderDetailResponseDataOrdersLineItemsItemTax read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }
}

