### 请求 /system/sms-template/send-sms 接口 => 成功
POST {{baseUrl}}/system/sms-template/send-sms
Authorization: Bearer {{token}}
Content-Type: application/json
tenant-id: {{adminTenentId}}

{
  "templateCode": "test_01",
  "mobile": "156016913900",
  "params": {
    "key01": "value01",
    "key02": "value02"
  }
}
