### 获得订单交易的分页 TODO
GET {{appApi}}/product/spu/page?pageNo=1&pageSize=10
Authorization: Bearer {{appToken}}
tenant-id: {{appTenentId}}

### 获得商品 SPU 明细
GET {{appApi}}/product/spu/get-detail?id=4
tenant-id: {{appTenentId}}
