### 请求 /transfer
PUT {{baseUrl}}/crm/customer/transfer
Content-Type: application/json
Authorization: Bearer {{token}}
tenant-id: {{adminTenentId}}

{
  "id": 11,
  "newOwnerUserId": 127,
  "oldOwnerPermissionLevel": 2
}


